<?php
/**
 * Auto-generated CSS Variable Mappings
 *
 * This mapping array is auto-generated from schema files.
 * Generated at: 2025-11-23T23:21:53.145Z
 *
 * This file is used by theme-css-generator.php for:
 * - Mapping attribute names to CSS variable names
 * - Identifying which numeric properties should NOT have units
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Attribute name to CSS variable name mappings
 */
$mappings = array(
    'accordion' => array(
      'titleColor' => array( 'cssVar' => 'accordion-title-color', 'unit' => null, 'type' => 'string' ),
      'titleBackgroundColor' => array( 'cssVar' => 'accordion-title-bg', 'unit' => null, 'type' => 'string' ),
      'hoverTitleColor' => array( 'cssVar' => 'accordion-title-hover-color', 'unit' => null, 'type' => 'string' ),
      'hoverTitleBackgroundColor' => array( 'cssVar' => 'accordion-title-hover-bg', 'unit' => null, 'type' => 'string' ),
      'contentColor' => array( 'cssVar' => 'accordion-content-color', 'unit' => null, 'type' => 'string' ),
      'contentBackgroundColor' => array( 'cssVar' => 'accordion-content-bg', 'unit' => null, 'type' => 'string' ),
      'accordionBorderColor' => array( 'cssVar' => 'accordion-border-color', 'unit' => null, 'type' => 'string' ),
      'dividerBorderColor' => array( 'cssVar' => 'accordion-divider-color', 'unit' => null, 'type' => 'string' ),
      'iconColor' => array( 'cssVar' => 'accordion-icon-color', 'unit' => null, 'type' => 'string' ),
      'titleFontSize' => array( 'cssVar' => 'accordion-title-font-size', 'unit' => 'px', 'type' => 'number' ),
      'titleFontWeight' => array( 'cssVar' => 'accordion-title-font-weight', 'unit' => null, 'type' => 'string' ),
      'titleFontFamily' => array( 'cssVar' => 'accordion-title-font-family', 'unit' => null, 'type' => 'string' ),
      'titleLineHeight' => array( 'cssVar' => 'accordion-title-line-height', 'unit' => null, 'type' => 'number' ),
      'titleFontStyle' => array( 'cssVar' => 'accordion-title-font-style', 'unit' => null, 'type' => 'string' ),
      'titleTextTransform' => array( 'cssVar' => 'accordion-title-text-transform', 'unit' => null, 'type' => 'string' ),
      'titleTextDecoration' => array( 'cssVar' => 'accordion-title-text-decoration', 'unit' => null, 'type' => 'string' ),
      'titleAlignment' => array( 'cssVar' => 'accordion-title-alignment', 'unit' => null, 'type' => 'string' ),
      'contentFontSize' => array( 'cssVar' => 'accordion-content-font-size', 'unit' => 'px', 'type' => 'number' ),
      'contentFontWeight' => array( 'cssVar' => 'accordion-content-font-weight', 'unit' => null, 'type' => 'string' ),
      'contentFontFamily' => array( 'cssVar' => 'accordion-content-font-family', 'unit' => null, 'type' => 'string' ),
      'contentLineHeight' => array( 'cssVar' => 'accordion-content-line-height', 'unit' => null, 'type' => 'number' ),
      'contentFontStyle' => array( 'cssVar' => 'accordion-content-font-style', 'unit' => null, 'type' => 'string' ),
      'contentTextTransform' => array( 'cssVar' => 'accordion-content-text-transform', 'unit' => null, 'type' => 'string' ),
      'contentTextDecoration' => array( 'cssVar' => 'accordion-content-text-decoration', 'unit' => null, 'type' => 'string' ),
      'accordionBorderThickness' => array( 'cssVar' => 'accordion-border-width', 'unit' => 'px', 'type' => 'number' ),
      'accordionBorderStyle' => array( 'cssVar' => 'accordion-border-style', 'unit' => null, 'type' => 'string' ),
      'accordionBorderRadius' => array( 'cssVar' => 'accordion-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'accordionShadow' => array( 'cssVar' => 'accordion-shadow', 'unit' => null, 'type' => 'string' ),
      'accordionShadowHover' => array( 'cssVar' => 'accordion-shadow-hover', 'unit' => null, 'type' => 'string' ),
      'dividerBorderThickness' => array( 'cssVar' => 'accordion-divider-width', 'unit' => 'px', 'type' => 'number' ),
      'dividerBorderStyle' => array( 'cssVar' => 'accordion-divider-style', 'unit' => null, 'type' => 'string' ),
      'titlePadding' => array( 'cssVar' => 'accordion-title-padding', 'unit' => 'px', 'type' => 'object' ),
      'contentPadding' => array( 'cssVar' => 'accordion-content-padding', 'unit' => 'px', 'type' => 'object' ),
      'accordionMarginBottom' => array( 'cssVar' => 'accordion-margin-bottom', 'unit' => 'px', 'type' => 'number' ),
      'itemSpacing' => array( 'cssVar' => 'accordion-item-spacing', 'unit' => 'px', 'type' => 'number' ),
      'iconSize' => array( 'cssVar' => 'accordion-icon-size', 'unit' => 'px', 'type' => 'number' ),
      'iconRotation' => array( 'cssVar' => 'accordion-icon-rotation', 'unit' => 'deg', 'type' => 'number' ),
    ),
    'tabs' => array(
      'titleColor' => array( 'cssVar' => 'tab-button-color', 'unit' => null, 'type' => 'string' ),
      'titleBackgroundColor' => array( 'cssVar' => 'tab-button-bg', 'unit' => null, 'type' => 'string' ),
      'hoverTitleColor' => array( 'cssVar' => 'tab-button-hover-color', 'unit' => null, 'type' => 'string' ),
      'hoverTitleBackgroundColor' => array( 'cssVar' => 'tab-button-hover-bg', 'unit' => null, 'type' => 'string' ),
      'activeTitleColor' => array( 'cssVar' => 'tab-button-active-color', 'unit' => null, 'type' => 'string' ),
      'activeTitleBackgroundColor' => array( 'cssVar' => 'tab-button-active-bg', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveColor' => array( 'cssVar' => 'tab-button-active-color', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveBackground' => array( 'cssVar' => 'tab-button-active-bg', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveBorderColor' => array( 'cssVar' => 'tab-button-active-border-color', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveBorderBottomColor' => array( 'cssVar' => 'tab-button-active-border-bottom-color', 'unit' => null, 'type' => 'string' ),
      'contentColor' => array( 'cssVar' => 'panel-color', 'unit' => null, 'type' => 'string' ),
      'contentBackgroundColor' => array( 'cssVar' => 'panel-bg', 'unit' => null, 'type' => 'string' ),
      'panelBackground' => array( 'cssVar' => 'panel-bg', 'unit' => null, 'type' => 'string' ),
      'panelColor' => array( 'cssVar' => 'panel-color', 'unit' => null, 'type' => 'string' ),
      'tabListBackground' => array( 'cssVar' => 'tabs-list-bg', 'unit' => null, 'type' => 'string' ),
      'tabBorderColor' => array( 'cssVar' => 'tab-button-border-color', 'unit' => null, 'type' => 'string' ),
      'containerBorderColor' => array( 'cssVar' => 'tabs-container-border-color', 'unit' => null, 'type' => 'string' ),
      'panelBorderColor' => array( 'cssVar' => 'panel-border-color', 'unit' => null, 'type' => 'string' ),
      'tabListBorderBottomColor' => array( 'cssVar' => 'tabs-list-border-bottom-color', 'unit' => null, 'type' => 'string' ),
      'dividerColor' => array( 'cssVar' => 'divider-color', 'unit' => null, 'type' => 'string' ),
      'dividerBorderColor' => array( 'cssVar' => 'divider-border-color', 'unit' => null, 'type' => 'string' ),
      'iconColor' => array( 'cssVar' => 'icon-color', 'unit' => null, 'type' => 'string' ),
      'titleFontSize' => array( 'cssVar' => 'tab-button-font-size', 'unit' => 'px', 'type' => 'number' ),
      'titleFontWeight' => array( 'cssVar' => 'tab-button-font-weight', 'unit' => null, 'type' => 'string' ),
      'titleFontFamily' => array( 'cssVar' => 'tab-button-font-family', 'unit' => null, 'type' => 'string' ),
      'titleLineHeight' => array( 'cssVar' => 'tab-button-line-height', 'unit' => null, 'type' => 'number' ),
      'titleFontStyle' => array( 'cssVar' => 'tab-button-font-style', 'unit' => null, 'type' => 'string' ),
      'titleTextTransform' => array( 'cssVar' => 'tab-button-text-transform', 'unit' => null, 'type' => 'string' ),
      'titleTextDecoration' => array( 'cssVar' => 'tab-button-text-decoration', 'unit' => null, 'type' => 'string' ),
      'titleAlignment' => array( 'cssVar' => 'tab-button-text-align', 'unit' => null, 'type' => 'string' ),
      'contentFontSize' => array( 'cssVar' => 'panel-font-size', 'unit' => 'px', 'type' => 'number' ),
      'contentFontWeight' => array( 'cssVar' => 'panel-font-weight', 'unit' => null, 'type' => 'string' ),
      'contentFontFamily' => array( 'cssVar' => 'panel-font-family', 'unit' => null, 'type' => 'string' ),
      'contentLineHeight' => array( 'cssVar' => 'panel-line-height', 'unit' => null, 'type' => 'number' ),
      'contentFontStyle' => array( 'cssVar' => 'panel-font-style', 'unit' => null, 'type' => 'string' ),
      'contentTextTransform' => array( 'cssVar' => 'panel-text-transform', 'unit' => null, 'type' => 'string' ),
      'contentTextDecoration' => array( 'cssVar' => 'panel-text-decoration', 'unit' => null, 'type' => 'string' ),
      'panelFontSize' => array( 'cssVar' => 'panel-font-size', 'unit' => 'px', 'type' => 'number' ),
      'panelLineHeight' => array( 'cssVar' => 'panel-line-height', 'unit' => null, 'type' => 'number' ),
      'tabBorderThickness' => array( 'cssVar' => 'tab-button-border-width', 'unit' => 'px', 'type' => 'number' ),
      'tabBorderStyle' => array( 'cssVar' => 'tab-button-border-style', 'unit' => null, 'type' => 'string' ),
      'tabBorderRadius' => array( 'cssVar' => 'tab-button-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'tabShadow' => array( 'cssVar' => 'tab-button-shadow', 'unit' => null, 'type' => 'string' ),
      'tabShadowHover' => array( 'cssVar' => 'tab-button-shadow-hover', 'unit' => null, 'type' => 'string' ),
      'tabButtonBorderRadius' => array( 'cssVar' => 'tab-button-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'containerBorderWidth' => array( 'cssVar' => 'tabs-container-border-width', 'unit' => 'px', 'type' => 'number' ),
      'containerBorderStyle' => array( 'cssVar' => 'tabs-container-border-style', 'unit' => null, 'type' => 'string' ),
      'containerBorderRadius' => array( 'cssVar' => 'tabs-container-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'containerShadow' => array( 'cssVar' => 'tabs-container-shadow', 'unit' => null, 'type' => 'string' ),
      'panelBorderWidth' => array( 'cssVar' => 'panel-border-width', 'unit' => 'px', 'type' => 'number' ),
      'panelBorderStyle' => array( 'cssVar' => 'panel-border-style', 'unit' => null, 'type' => 'string' ),
      'panelBorderRadius' => array( 'cssVar' => 'panel-border-radius', 'unit' => 'px', 'type' => 'number' ),
      'tabListBorderBottomWidth' => array( 'cssVar' => 'tabs-list-border-bottom-width', 'unit' => 'px', 'type' => 'number' ),
      'tabListBorderBottomStyle' => array( 'cssVar' => 'tabs-list-border-bottom-style', 'unit' => null, 'type' => 'string' ),
      'dividerThickness' => array( 'cssVar' => 'divider-thickness', 'unit' => 'px', 'type' => 'number' ),
      'dividerStyle' => array( 'cssVar' => 'divider-style', 'unit' => null, 'type' => 'string' ),
      'accordionBorderThickness' => array( 'cssVar' => 'tabs-border-width', 'unit' => 'px', 'type' => 'number' ),
      'accordionBorderStyle' => array( 'cssVar' => 'tabs-border-style', 'unit' => null, 'type' => 'string' ),
      'accordionBorderRadius' => array( 'cssVar' => 'tabs-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'accordionShadow' => array( 'cssVar' => 'tabs-shadow', 'unit' => null, 'type' => 'string' ),
      'dividerBorderThickness' => array( 'cssVar' => 'divider-border-thickness', 'unit' => 'px', 'type' => 'number' ),
      'dividerBorderStyle' => array( 'cssVar' => 'divider-border-style', 'unit' => null, 'type' => 'string' ),
      'titlePadding' => array( 'cssVar' => 'tab-button-padding', 'unit' => 'px', 'type' => 'object' ),
      'contentPadding' => array( 'cssVar' => 'panel-padding', 'unit' => 'px', 'type' => 'object' ),
      'panelPadding' => array( 'cssVar' => 'panel-padding', 'unit' => 'px', 'type' => 'object' ),
      'tabListPadding' => array( 'cssVar' => 'tabs-list-padding', 'unit' => 'px', 'type' => 'object' ),
      'tabListGap' => array( 'cssVar' => 'tabs-list-gap', 'unit' => 'px', 'type' => 'number' ),
      'tabsAlignment' => array( 'cssVar' => 'tabs-alignment', 'unit' => null, 'type' => 'string' ),
      'verticalTabListWidth' => array( 'cssVar' => 'vertical-tab-list-width', 'unit' => 'px', 'type' => 'number' ),
      'accordionMarginBottom' => array( 'cssVar' => 'tabs-margin-bottom', 'unit' => 'px', 'type' => 'number' ),
      'itemSpacing' => array( 'cssVar' => 'tabs-item-spacing', 'unit' => 'px', 'type' => 'number' ),
      'iconSize' => array( 'cssVar' => 'icon-size', 'unit' => 'px', 'type' => 'number' ),
      'iconRotation' => array( 'cssVar' => 'icon-rotation', 'unit' => 'deg', 'type' => 'number' ),
    ),
    'toc' => array(
      'wrapperBackgroundColor' => array( 'cssVar' => 'toc-wrapper-background-color', 'unit' => null, 'type' => 'string' ),
      'wrapperBorderColor' => array( 'cssVar' => 'toc-wrapper-border-color', 'unit' => null, 'type' => 'string' ),
      'titleColor' => array( 'cssVar' => 'toc-title-color', 'unit' => null, 'type' => 'string' ),
      'titleBackgroundColor' => array( 'cssVar' => 'toc-title-background-color', 'unit' => null, 'type' => 'string' ),
      'linkColor' => array( 'cssVar' => 'toc-link-color', 'unit' => null, 'type' => 'string' ),
      'linkHoverColor' => array( 'cssVar' => 'toc-link-hover-color', 'unit' => null, 'type' => 'string' ),
      'linkActiveColor' => array( 'cssVar' => 'toc-link-active-color', 'unit' => null, 'type' => 'string' ),
      'linkVisitedColor' => array( 'cssVar' => 'toc-link-visited-color', 'unit' => null, 'type' => 'string' ),
      'numberingColor' => array( 'cssVar' => 'toc-numbering-color', 'unit' => null, 'type' => 'string' ),
      'level1Color' => array( 'cssVar' => 'toc-level1-color', 'unit' => null, 'type' => 'string' ),
      'level2Color' => array( 'cssVar' => 'toc-level2-color', 'unit' => null, 'type' => 'string' ),
      'level3PlusColor' => array( 'cssVar' => 'toc-level3-plus-color', 'unit' => null, 'type' => 'string' ),
      'collapseIconColor' => array( 'cssVar' => 'toc-collapse-icon-color', 'unit' => null, 'type' => 'string' ),
      'titleFontSize' => array( 'cssVar' => 'toc-title-font-size', 'unit' => 'px', 'type' => 'number' ),
      'titleFontWeight' => array( 'cssVar' => 'toc-title-font-weight', 'unit' => null, 'type' => 'string' ),
      'titleTextTransform' => array( 'cssVar' => 'toc-title-text-transform', 'unit' => null, 'type' => 'string' ),
      'titleAlignment' => array( 'cssVar' => 'toc-title-alignment', 'unit' => null, 'type' => 'string' ),
      'level1FontSize' => array( 'cssVar' => 'toc-level1-font-size', 'unit' => 'px', 'type' => 'number' ),
      'level1FontWeight' => array( 'cssVar' => 'toc-level1-font-weight', 'unit' => null, 'type' => 'string' ),
      'level1FontStyle' => array( 'cssVar' => 'toc-level1-font-style', 'unit' => null, 'type' => 'string' ),
      'level1TextTransform' => array( 'cssVar' => 'toc-level1-text-transform', 'unit' => null, 'type' => 'string' ),
      'level1TextDecoration' => array( 'cssVar' => 'toc-level1-text-decoration', 'unit' => null, 'type' => 'string' ),
      'level2FontSize' => array( 'cssVar' => 'toc-level2-font-size', 'unit' => 'px', 'type' => 'number' ),
      'level2FontWeight' => array( 'cssVar' => 'toc-level2-font-weight', 'unit' => null, 'type' => 'string' ),
      'level2FontStyle' => array( 'cssVar' => 'toc-level2-font-style', 'unit' => null, 'type' => 'string' ),
      'level2TextTransform' => array( 'cssVar' => 'toc-level2-text-transform', 'unit' => null, 'type' => 'string' ),
      'level2TextDecoration' => array( 'cssVar' => 'toc-level2-text-decoration', 'unit' => null, 'type' => 'string' ),
      'level3PlusFontSize' => array( 'cssVar' => 'toc-level3-plus-font-size', 'unit' => 'px', 'type' => 'number' ),
      'level3PlusFontWeight' => array( 'cssVar' => 'toc-level3-plus-font-weight', 'unit' => null, 'type' => 'string' ),
      'level3PlusFontStyle' => array( 'cssVar' => 'toc-level3-plus-font-style', 'unit' => null, 'type' => 'string' ),
      'level3PlusTextTransform' => array( 'cssVar' => 'toc-level3-plus-text-transform', 'unit' => null, 'type' => 'string' ),
      'level3PlusTextDecoration' => array( 'cssVar' => 'toc-level3-plus-text-decoration', 'unit' => null, 'type' => 'string' ),
      'wrapperBorderWidth' => array( 'cssVar' => 'toc-border-width', 'unit' => 'px', 'type' => 'number' ),
      'wrapperBorderStyle' => array( 'cssVar' => 'toc-border-style', 'unit' => null, 'type' => 'string' ),
      'wrapperBorderRadius' => array( 'cssVar' => 'toc-border-radius', 'unit' => 'px', 'type' => 'number' ),
      'wrapperShadow' => array( 'cssVar' => 'toc-wrapper-shadow', 'unit' => null, 'type' => 'string' ),
      'wrapperShadowHover' => array( 'cssVar' => 'toc-wrapper-shadow-hover', 'unit' => null, 'type' => 'string' ),
      'wrapperPadding' => array( 'cssVar' => 'toc-wrapper-padding', 'unit' => 'px', 'type' => 'number' ),
      'listPaddingLeft' => array( 'cssVar' => 'toc-list-padding-left', 'unit' => 'px', 'type' => 'number' ),
      'itemSpacing' => array( 'cssVar' => 'toc-item-spacing', 'unit' => 'px', 'type' => 'number' ),
      'levelIndent' => array( 'cssVar' => 'toc-level-indent', 'unit' => 'px', 'type' => 'number' ),
      'positionTop' => array( 'cssVar' => 'toc-position-top', 'unit' => 'px', 'type' => 'number' ),
      'zIndex' => array( 'cssVar' => 'toc-z-index', 'unit' => null, 'type' => 'number' ),
      'collapseIconSize' => array( 'cssVar' => 'toc-collapse-icon-size', 'unit' => 'px', 'type' => 'number' ),
    ),
  );

// Return mappings for use in theme-css-generator.php
return $mappings;
