<?php
/**
 * CSS Default Values
 *
 * Auto-generated from assets/css/tabs.css
 * Generated: 2025-11-17T11:04:09.826Z
 *
 * DO NOT EDIT MANUALLY - Changes will be overwritten on build
 */

return array(
  'containerBackground' => 'transparent',
  'containerPadding' => '0',
  'containerBorderWidth' => '0',
  'containerBorderStyle' => 'solid',
  'containerBorderColor' => 'transparent',
  'containerBorderRadius' => '4',
  'containerShadow' => 'none',
  'tabListBackground' => '#f5f5f5',
  'tabListBorderBottomWidth' => '2',
  'tabListBorderBottomStyle' => 'solid',
  'tabListBorderBottomColor' => '#ddd',
  'tabListGap' => '4',
  'tabListPadding' => '8',
  'tabsAlignment' => 'left',
  'tabButtonColor' => '#666',
  'tabButtonBackground' => 'transparent',
  'tabButtonBorderWidth' => '1',
  'tabButtonBorderStyle' => 'solid',
  'tabButtonBorderColor' => 'transparent',
  'tabButtonBorderRadiusTopLeft' => '4',
  'tabButtonBorderRadiusTopRight' => '4',
  'tabButtonBorderRadiusBottomLeft' => '0',
  'tabButtonBorderRadiusBottomRight' => '0',
  'tabButtonPadding' => '12px 24px',
  'tabButtonFontSize' => '16',
  'tabButtonFontWeight' => '500',
  'tabButtonFontStyle' => 'normal',
  'tabButtonTextTransform' => 'none',
  'tabButtonTextDecoration' => 'none',
  'tabButtonTextAlign' => 'center',
  'tabButtonHoverColor' => '#333',
  'tabButtonHoverBackground' => '#e8e8e8',
  'tabButtonHoverBorderColor' => '#ccc',
  'tabButtonActiveColor' => '#000',
  'tabButtonActiveBackground' => '#fff',
  'tabButtonActiveBorderColor' => '#ddd',
  'tabButtonActiveBorderBottomColor' => 'transparent',
  'panelBackground' => '#fff',
  'panelColor' => '#333',
  'panelBorderWidth' => '1',
  'panelBorderStyle' => 'solid',
  'panelBorderColor' => '#ddd',
  'panelBorderRadius' => '0',
  'panelPadding' => '24',
  'panelFontSize' => '16',
  'panelLineHeight' => '1.6',
  'dividerThickness' => '0',
  'dividerStyle' => 'solid',
  'dividerColor' => '#ddd',
  'iconSize' => '18',
  'iconColor' => 'inherit',
  'iconSpacing' => '8',
  'transitionDuration' => '200',
  'transitionEasing' => 'ease-in-out',
  'responsiveBreakpoint' => '768',
  'verticalTabListWidth' => '200',
  'verticalTabButtonTextAlign' => 'left',
);
