<?php
/**
 * Auto-generated CSS Variable Mappings
 *
 * This mapping array is auto-generated from schema files.
 * Generated at: 2025-12-29T02:28:32.327Z
 *
 * This file is used by theme-css-generator.php for:
 * - Mapping attribute names to CSS variable names
 * - Identifying which numeric properties should NOT have units
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Attribute name to CSS variable name mappings
 */
$mappings = array(
    'accordion' => array(
      'dividerWidth' => array( 'cssVar' => 'accordion-divider-width', 'unit' => null, 'type' => 'object' ),
      'dividerColor' => array( 'cssVar' => 'accordion-divider-color', 'unit' => null, 'type' => 'object' ),
      'dividerStyle' => array( 'cssVar' => 'accordion-divider-style', 'unit' => null, 'type' => 'object' ),
      'borderWidth' => array( 'cssVar' => 'accordion-border-width', 'unit' => null, 'type' => 'object' ),
      'borderRadius' => array( 'cssVar' => 'accordion-border-radius', 'unit' => null, 'type' => 'object' ),
      'shadow' => array( 'cssVar' => 'accordion-shadow', 'unit' => null, 'type' => 'array' ),
      'borderColor' => array( 'cssVar' => 'accordion-border-color', 'unit' => null, 'type' => 'object' ),
      'borderStyle' => array( 'cssVar' => 'accordion-border-style', 'unit' => null, 'type' => 'object' ),
      'headerPadding' => array( 'cssVar' => 'accordion-header-padding', 'unit' => null, 'type' => 'object' ),
      'contentPadding' => array( 'cssVar' => 'accordion-content-padding', 'unit' => null, 'type' => 'object' ),
      'blockMargin' => array( 'cssVar' => 'accordion-block-margin', 'unit' => null, 'type' => 'object' ),
      'titleColor' => array( 'cssVar' => 'accordion-title-color', 'unit' => null, 'type' => 'string' ),
      'titleBackgroundColor' => array( 'cssVar' => 'accordion-title-bg', 'unit' => null, 'type' => 'string' ),
      'hoverTitleColor' => array( 'cssVar' => 'accordion-title-hover-color', 'unit' => null, 'type' => 'string' ),
      'hoverTitleBackgroundColor' => array( 'cssVar' => 'accordion-title-hover-bg', 'unit' => null, 'type' => 'string' ),
      'contentTextColor' => array( 'cssVar' => 'accordion-content-color', 'unit' => null, 'type' => 'string' ),
      'contentBackgroundColor' => array( 'cssVar' => 'accordion-content-bg', 'unit' => null, 'type' => 'string' ),
      'contentFontFamily' => array( 'cssVar' => 'accordion-content-font-family', 'unit' => null, 'type' => 'string' ),
      'contentFontSize' => array( 'cssVar' => 'accordion-content-font-size', 'unit' => null, 'type' => 'string' ),
      'contentLineHeight' => array( 'cssVar' => 'accordion-content-line-height', 'unit' => null, 'type' => 'number' ),
      'titleFontFamily' => array( 'cssVar' => 'accordion-title-font-family', 'unit' => null, 'type' => 'string' ),
      'titleFontSize' => array( 'cssVar' => 'accordion-title-font-size', 'unit' => null, 'type' => 'string' ),
      'titleFontWeight' => array( 'cssVar' => 'accordion-title-font-weight', 'unit' => null, 'type' => 'number' ),
      'titleDecorationColor' => array( 'cssVar' => 'accordion-title-decoration-color', 'unit' => null, 'type' => 'string' ),
      'titleDecorationStyle' => array( 'cssVar' => 'accordion-title-decoration-style', 'unit' => null, 'type' => 'string' ),
      'titleDecorationWidth' => array( 'cssVar' => 'accordion-title-decoration-width', 'unit' => null, 'type' => 'string' ),
      'titleLetterSpacing' => array( 'cssVar' => 'accordion-title-letter-spacing', 'unit' => null, 'type' => 'string' ),
      'titleTextTransform' => array( 'cssVar' => 'accordion-title-text-transform', 'unit' => null, 'type' => 'string' ),
      'titleLineHeight' => array( 'cssVar' => 'accordion-title-line-height', 'unit' => null, 'type' => 'number' ),
      'titleAlignment' => array( 'cssVar' => 'accordion-title-alignment', 'unit' => null, 'type' => 'string' ),
      'titleOffsetX' => array( 'cssVar' => 'accordion-title-offset-x', 'unit' => null, 'type' => 'string' ),
      'titleOffsetY' => array( 'cssVar' => 'accordion-title-offset-y', 'unit' => null, 'type' => 'string' ),
      'titleTextShadow' => array( 'cssVar' => 'accordion-title-text-shadow', 'unit' => null, 'type' => 'array' ),
      'iconColor' => array( 'cssVar' => 'accordion-icon-color', 'unit' => null, 'type' => 'string' ),
      'iconSize' => array( 'cssVar' => 'accordion-icon-size', 'unit' => null, 'type' => 'string' ),
      'iconRotation' => array( 'cssVar' => 'accordion-icon-rotation', 'unit' => null, 'type' => 'string' ),
      'animationDuration' => array( 'cssVar' => 'accordion-animation-duration', 'unit' => null, 'type' => 'string' ),
      'animationEasing' => array( 'cssVar' => 'accordion-animation-easing', 'unit' => null, 'type' => 'string' ),
    ),
    'tabs' => array(
      'borderColor' => array( 'cssVar' => 'tabs-border-color', 'unit' => null, 'type' => 'object' ),
      'borderWidth' => array( 'cssVar' => 'tabs-border-width', 'unit' => null, 'type' => 'number' ),
      'borderStyle' => array( 'cssVar' => 'tabs-border-style', 'unit' => null, 'type' => 'object' ),
      'borderRadius' => array( 'cssVar' => 'tabs-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'shadow' => array( 'cssVar' => 'tabs-border-shadow', 'unit' => null, 'type' => 'string' ),
      'shadowHover' => array( 'cssVar' => 'tabs-border-shadow-hover', 'unit' => null, 'type' => 'string' ),
      'tabButtonColor' => array( 'cssVar' => 'tabs-button-color', 'unit' => null, 'type' => 'string' ),
      'tabButtonBackgroundColor' => array( 'cssVar' => 'tabs-button-bg', 'unit' => null, 'type' => 'string' ),
      'tabButtonHoverColor' => array( 'cssVar' => 'tabs-button-hover-color', 'unit' => null, 'type' => 'string' ),
      'tabButtonHoverBackgroundColor' => array( 'cssVar' => 'tabs-button-hover-bg', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveColor' => array( 'cssVar' => 'tabs-button-active-color', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveBackgroundColor' => array( 'cssVar' => 'tabs-button-active-bg', 'unit' => null, 'type' => 'string' ),
      'tabButtonFontSize' => array( 'cssVar' => 'tabs-button-font-size', 'unit' => null, 'type' => 'number' ),
      'tabButtonFontWeight' => array( 'cssVar' => 'tabs-button-font-weight', 'unit' => null, 'type' => 'string' ),
      'tabButtonFontStyle' => array( 'cssVar' => 'tabs-button-font-style', 'unit' => null, 'type' => 'string' ),
      'tabButtonTextTransform' => array( 'cssVar' => 'tabs-button-text-transform', 'unit' => null, 'type' => 'string' ),
      'tabButtonTextDecoration' => array( 'cssVar' => 'tabs-button-text-decoration', 'unit' => null, 'type' => 'string' ),
      'tabButtonTextAlign' => array( 'cssVar' => 'tabs-button-text-align', 'unit' => null, 'type' => 'string' ),
      'tabButtonPadding' => array( 'cssVar' => 'tabs-button-padding', 'unit' => null, 'type' => 'number' ),
      'tabButtonActiveFontWeight' => array( 'cssVar' => 'tabs-button-active-font-weight', 'unit' => null, 'type' => 'string' ),
      'tabButtonBorderColor' => array( 'cssVar' => 'tabs-button-border-color', 'unit' => null, 'type' => 'object' ),
      'tabButtonActiveBorderColor' => array( 'cssVar' => 'tabs-button-active-border-color', 'unit' => null, 'type' => 'object' ),
      'tabButtonBorderWidth' => array( 'cssVar' => 'tabs-button-border-width', 'unit' => null, 'type' => 'number' ),
      'tabButtonBorderStyle' => array( 'cssVar' => 'tabs-button-border-style', 'unit' => null, 'type' => 'object' ),
      'tabButtonBorderRadius' => array( 'cssVar' => 'tabs-button-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'tabButtonShadow' => array( 'cssVar' => 'tabs-button-border-shadow', 'unit' => null, 'type' => 'string' ),
      'tabButtonShadowHover' => array( 'cssVar' => 'tabs-button-border-shadow-hover', 'unit' => null, 'type' => 'string' ),
      'enableFocusBorder' => array( 'cssVar' => 'tabs-enable-focus-border', 'unit' => null, 'type' => 'boolean' ),
      'tabButtonActiveContentBorderColor' => array( 'cssVar' => 'tabs-button-active-content-border-color', 'unit' => null, 'type' => 'string' ),
      'tabButtonActiveContentBorderWidth' => array( 'cssVar' => 'tabs-button-active-content-border-width', 'unit' => null, 'type' => 'number' ),
      'tabButtonActiveContentBorderStyle' => array( 'cssVar' => 'tabs-button-active-content-border-style', 'unit' => null, 'type' => 'string' ),
      'tabListBackgroundColor' => array( 'cssVar' => 'tabs-list-bg', 'unit' => null, 'type' => 'string' ),
      'tabsRowBorderColor' => array( 'cssVar' => 'tabs-row-border-color', 'unit' => null, 'type' => 'object' ),
      'tabsRowBorderWidth' => array( 'cssVar' => 'tabs-row-border-width', 'unit' => null, 'type' => 'number' ),
      'tabsRowBorderStyle' => array( 'cssVar' => 'tabs-row-border-style', 'unit' => null, 'type' => 'object' ),
      'tabsRowSpacing' => array( 'cssVar' => 'tabs-row-spacing', 'unit' => null, 'type' => 'number' ),
      'tabsButtonGap' => array( 'cssVar' => 'tabs-button-gap', 'unit' => null, 'type' => 'number' ),
      'tabListAlignment' => array( 'cssVar' => 'tabs-list-align', 'unit' => null, 'type' => 'string' ),
      'enableTabsListContentBorder' => array( 'cssVar' => 'tabs-enable-list-divider-border', 'unit' => null, 'type' => 'boolean' ),
      'tabsListContentBorderColor' => array( 'cssVar' => 'tabs-list-divider-border-color', 'unit' => null, 'type' => 'string' ),
      'tabsListContentBorderWidth' => array( 'cssVar' => 'tabs-list-divider-border-width', 'unit' => null, 'type' => 'number' ),
      'tabsListContentBorderStyle' => array( 'cssVar' => 'tabs-list-divider-border-style', 'unit' => null, 'type' => 'string' ),
      'panelBackgroundColor' => array( 'cssVar' => 'tabs-panel-bg', 'unit' => null, 'type' => 'string' ),
      'panelBorderColor' => array( 'cssVar' => 'tabs-panel-border-color', 'unit' => null, 'type' => 'object' ),
      'panelBorderWidth' => array( 'cssVar' => 'tabs-panel-border-width', 'unit' => null, 'type' => 'number' ),
      'panelBorderStyle' => array( 'cssVar' => 'tabs-panel-border-style', 'unit' => null, 'type' => 'object' ),
      'panelBorderRadius' => array( 'cssVar' => 'tabs-panel-border-radius', 'unit' => 'px', 'type' => 'object' ),
      'showIcon' => array( 'cssVar' => 'tabs-show-icon', 'unit' => null, 'type' => 'boolean' ),
      'iconPosition' => array( 'cssVar' => 'tabs-icon-position', 'unit' => null, 'type' => 'string' ),
      'iconColor' => array( 'cssVar' => 'tabs-icon-color', 'unit' => null, 'type' => 'string' ),
      'iconSize' => array( 'cssVar' => 'tabs-icon-size', 'unit' => null, 'type' => 'number' ),
      'iconTypeClosed' => array( 'cssVar' => 'tabs-icon-type-closed', 'unit' => null, 'type' => 'string' ),
      'iconTypeOpen' => array( 'cssVar' => 'tabs-icon-type-open', 'unit' => null, 'type' => 'string' ),
      'iconRotation' => array( 'cssVar' => 'tabs-icon-rotation-base', 'unit' => null, 'type' => 'number' ),
      'iconRotationActive' => array( 'cssVar' => 'tabs-icon-rotation-active', 'unit' => null, 'type' => 'number' ),
    ),
    'toc' => array(
      'wrapperBackgroundColor' => array( 'cssVar' => 'toc-wrapper-background-color', 'unit' => null, 'type' => 'string' ),
      'blockBorderColor' => array( 'cssVar' => 'toc-border-color', 'unit' => null, 'type' => 'object' ),
      'titleColor' => array( 'cssVar' => 'toc-title-color', 'unit' => null, 'type' => 'string' ),
      'titleBackgroundColor' => array( 'cssVar' => 'toc-title-background-color', 'unit' => null, 'type' => 'string' ),
      'hoverTitleColor' => array( 'cssVar' => 'toc-title-hover-color', 'unit' => null, 'type' => 'string' ),
      'hoverTitleBackgroundColor' => array( 'cssVar' => 'toc-title-hover-bg', 'unit' => null, 'type' => 'string' ),
      'linkColor' => array( 'cssVar' => 'toc-link-color', 'unit' => null, 'type' => 'string' ),
      'linkHoverColor' => array( 'cssVar' => 'toc-link-hover-color', 'unit' => null, 'type' => 'string' ),
      'linkActiveColor' => array( 'cssVar' => 'toc-link-active-color', 'unit' => null, 'type' => 'string' ),
      'linkVisitedColor' => array( 'cssVar' => 'toc-link-visited-color', 'unit' => null, 'type' => 'string' ),
      'h1Color' => array( 'cssVar' => 'toc-h1-color', 'unit' => null, 'type' => 'string' ),
      'h1HoverColor' => array( 'cssVar' => 'toc-h1-hover-color', 'unit' => null, 'type' => 'string' ),
      'h1VisitedColor' => array( 'cssVar' => 'toc-h1-visited-color', 'unit' => null, 'type' => 'string' ),
      'h1ActiveColor' => array( 'cssVar' => 'toc-h1-active-color', 'unit' => null, 'type' => 'string' ),
      'h1FontSize' => array( 'cssVar' => 'toc-h1-font-size', 'unit' => null, 'type' => 'string' ),
      'h1FontWeight' => array( 'cssVar' => 'toc-h1-font-weight', 'unit' => null, 'type' => 'string' ),
      'h1FontStyle' => array( 'cssVar' => 'toc-h1-font-style', 'unit' => null, 'type' => 'string' ),
      'h1TextTransform' => array( 'cssVar' => 'toc-h1-text-transform', 'unit' => null, 'type' => 'string' ),
      'h1TextDecoration' => array( 'cssVar' => 'toc-h1-text-decoration', 'unit' => null, 'type' => 'string' ),
      'h2Color' => array( 'cssVar' => 'toc-h2-color', 'unit' => null, 'type' => 'string' ),
      'h2HoverColor' => array( 'cssVar' => 'toc-h2-hover-color', 'unit' => null, 'type' => 'string' ),
      'h2VisitedColor' => array( 'cssVar' => 'toc-h2-visited-color', 'unit' => null, 'type' => 'string' ),
      'h2ActiveColor' => array( 'cssVar' => 'toc-h2-active-color', 'unit' => null, 'type' => 'string' ),
      'h2FontSize' => array( 'cssVar' => 'toc-h2-font-size', 'unit' => null, 'type' => 'string' ),
      'h2FontWeight' => array( 'cssVar' => 'toc-h2-font-weight', 'unit' => null, 'type' => 'string' ),
      'h2FontStyle' => array( 'cssVar' => 'toc-h2-font-style', 'unit' => null, 'type' => 'string' ),
      'h2TextTransform' => array( 'cssVar' => 'toc-h2-text-transform', 'unit' => null, 'type' => 'string' ),
      'h2TextDecoration' => array( 'cssVar' => 'toc-h2-text-decoration', 'unit' => null, 'type' => 'string' ),
      'h3Color' => array( 'cssVar' => 'toc-h3-color', 'unit' => null, 'type' => 'string' ),
      'h3HoverColor' => array( 'cssVar' => 'toc-h3-hover-color', 'unit' => null, 'type' => 'string' ),
      'h3VisitedColor' => array( 'cssVar' => 'toc-h3-visited-color', 'unit' => null, 'type' => 'string' ),
      'h3ActiveColor' => array( 'cssVar' => 'toc-h3-active-color', 'unit' => null, 'type' => 'string' ),
      'h3FontSize' => array( 'cssVar' => 'toc-h3-font-size', 'unit' => null, 'type' => 'string' ),
      'h3FontWeight' => array( 'cssVar' => 'toc-h3-font-weight', 'unit' => null, 'type' => 'string' ),
      'h3FontStyle' => array( 'cssVar' => 'toc-h3-font-style', 'unit' => null, 'type' => 'string' ),
      'h3TextTransform' => array( 'cssVar' => 'toc-h3-text-transform', 'unit' => null, 'type' => 'string' ),
      'h3TextDecoration' => array( 'cssVar' => 'toc-h3-text-decoration', 'unit' => null, 'type' => 'string' ),
      'h4Color' => array( 'cssVar' => 'toc-h4-color', 'unit' => null, 'type' => 'string' ),
      'h4HoverColor' => array( 'cssVar' => 'toc-h4-hover-color', 'unit' => null, 'type' => 'string' ),
      'h4VisitedColor' => array( 'cssVar' => 'toc-h4-visited-color', 'unit' => null, 'type' => 'string' ),
      'h4ActiveColor' => array( 'cssVar' => 'toc-h4-active-color', 'unit' => null, 'type' => 'string' ),
      'h4FontSize' => array( 'cssVar' => 'toc-h4-font-size', 'unit' => null, 'type' => 'string' ),
      'h4FontWeight' => array( 'cssVar' => 'toc-h4-font-weight', 'unit' => null, 'type' => 'string' ),
      'h4FontStyle' => array( 'cssVar' => 'toc-h4-font-style', 'unit' => null, 'type' => 'string' ),
      'h4TextTransform' => array( 'cssVar' => 'toc-h4-text-transform', 'unit' => null, 'type' => 'string' ),
      'h4TextDecoration' => array( 'cssVar' => 'toc-h4-text-decoration', 'unit' => null, 'type' => 'string' ),
      'h5Color' => array( 'cssVar' => 'toc-h5-color', 'unit' => null, 'type' => 'string' ),
      'h5HoverColor' => array( 'cssVar' => 'toc-h5-hover-color', 'unit' => null, 'type' => 'string' ),
      'h5VisitedColor' => array( 'cssVar' => 'toc-h5-visited-color', 'unit' => null, 'type' => 'string' ),
      'h5ActiveColor' => array( 'cssVar' => 'toc-h5-active-color', 'unit' => null, 'type' => 'string' ),
      'h5FontSize' => array( 'cssVar' => 'toc-h5-font-size', 'unit' => null, 'type' => 'string' ),
      'h5FontWeight' => array( 'cssVar' => 'toc-h5-font-weight', 'unit' => null, 'type' => 'string' ),
      'h5FontStyle' => array( 'cssVar' => 'toc-h5-font-style', 'unit' => null, 'type' => 'string' ),
      'h5TextTransform' => array( 'cssVar' => 'toc-h5-text-transform', 'unit' => null, 'type' => 'string' ),
      'h5TextDecoration' => array( 'cssVar' => 'toc-h5-text-decoration', 'unit' => null, 'type' => 'string' ),
      'h6Color' => array( 'cssVar' => 'toc-h6-color', 'unit' => null, 'type' => 'string' ),
      'h6HoverColor' => array( 'cssVar' => 'toc-h6-hover-color', 'unit' => null, 'type' => 'string' ),
      'h6VisitedColor' => array( 'cssVar' => 'toc-h6-visited-color', 'unit' => null, 'type' => 'string' ),
      'h6ActiveColor' => array( 'cssVar' => 'toc-h6-active-color', 'unit' => null, 'type' => 'string' ),
      'h6FontSize' => array( 'cssVar' => 'toc-h6-font-size', 'unit' => null, 'type' => 'string' ),
      'h6FontWeight' => array( 'cssVar' => 'toc-h6-font-weight', 'unit' => null, 'type' => 'string' ),
      'h6FontStyle' => array( 'cssVar' => 'toc-h6-font-style', 'unit' => null, 'type' => 'string' ),
      'h6TextTransform' => array( 'cssVar' => 'toc-h6-text-transform', 'unit' => null, 'type' => 'string' ),
      'h6TextDecoration' => array( 'cssVar' => 'toc-h6-text-decoration', 'unit' => null, 'type' => 'string' ),
      'iconSize' => array( 'cssVar' => 'toc-icon-size', 'unit' => null, 'type' => 'string' ),
      'iconRotation' => array( 'cssVar' => 'toc-icon-rotation', 'unit' => null, 'type' => 'string' ),
      'iconColor' => array( 'cssVar' => 'toc-icon-color', 'unit' => null, 'type' => 'string' ),
      'titleFontSize' => array( 'cssVar' => 'toc-title-font-size', 'unit' => null, 'type' => 'string' ),
      'titleFontWeight' => array( 'cssVar' => 'toc-title-font-weight', 'unit' => null, 'type' => 'string' ),
      'titleFontStyle' => array( 'cssVar' => 'toc-title-font-style', 'unit' => null, 'type' => 'string' ),
      'titleTextTransform' => array( 'cssVar' => 'toc-title-text-transform', 'unit' => null, 'type' => 'string' ),
      'titleTextDecoration' => array( 'cssVar' => 'toc-title-text-decoration', 'unit' => null, 'type' => 'string' ),
      'titleAlignment' => array( 'cssVar' => 'toc-title-alignment', 'unit' => null, 'type' => 'string' ),
      'blockBorderWidth' => array( 'cssVar' => 'toc-border-width', 'unit' => null, 'type' => 'string' ),
      'blockBorderStyle' => array( 'cssVar' => 'toc-border-style', 'unit' => null, 'type' => 'object' ),
      'blockBorderRadius' => array( 'cssVar' => 'toc-border-radius', 'unit' => null, 'type' => 'object' ),
      'blockShadow' => array( 'cssVar' => 'toc-border-shadow', 'unit' => null, 'type' => 'string' ),
      'blockShadowHover' => array( 'cssVar' => 'toc-border-shadow-hover', 'unit' => null, 'type' => 'string' ),
      'wrapperPadding' => array( 'cssVar' => 'toc-wrapper-padding', 'unit' => null, 'type' => 'string' ),
      'itemSpacing' => array( 'cssVar' => 'toc-item-spacing', 'unit' => null, 'type' => 'string' ),
      'levelIndent' => array( 'cssVar' => 'toc-level-indent', 'unit' => null, 'type' => 'string' ),
      'positionTop' => array( 'cssVar' => 'toc-position-top', 'unit' => null, 'type' => 'string' ),
      'zIndex' => array( 'cssVar' => 'toc-z-index', 'unit' => null, 'type' => 'number' ),
    ),
  );

// Return mappings for use in theme-css-generator.php
return $mappings;
