<?php
/**
 * Auto-generated CSS Variable Mappings
 *
 * This mapping array is auto-generated from schema files.
 * Generated at: 2026-01-04T23:18:45.239Z
 *
 * This file is used by theme-css-generator.php for:
 * - Mapping attribute names to CSS variable names
 * - Identifying which numeric properties should NOT have units
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Attribute name to CSS variable name mappings
 */
$mappings = array(
    'accordion' => array(
      'showIcon' => array( 'cssVar' => 'accordion-icon-display', 'unit' => null, 'defaultUnit' => null, 'type' => 'boolean' ),
      'iconRotation' => array( 'cssVar' => 'accordion-icon-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconInactiveColor' => array( 'cssVar' => 'accordion-icon-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'iconInactiveRotation' => array( 'cssVar' => 'accordion-icon-initial-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconInactiveSize' => array( 'cssVar' => 'accordion-icon-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveMaxSize' => array( 'cssVar' => 'accordion-icon-max-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveOffsetX' => array( 'cssVar' => 'accordion-icon-offset-x', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveOffsetY' => array( 'cssVar' => 'accordion-icon-offset-y', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveColor' => array( 'cssVar' => 'accordion-icon-active-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'iconActiveRotation' => array( 'cssVar' => 'accordion-icon-active-initial-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconActiveSize' => array( 'cssVar' => 'accordion-icon-active-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveMaxSize' => array( 'cssVar' => 'accordion-icon-active-max-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveOffsetX' => array( 'cssVar' => 'accordion-icon-active-offset-x', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveOffsetY' => array( 'cssVar' => 'accordion-icon-active-offset-y', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'animationDuration' => array( 'cssVar' => 'accordion-animation-duration', 'unit' => null, 'defaultUnit' => 'ms', 'type' => 'string' ),
    ),
    'tabs' => array(
      'borderColor' => array( 'cssVar' => 'tabs-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'borderWidth' => array( 'cssVar' => 'tabs-border-width', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'borderStyle' => array( 'cssVar' => 'tabs-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'borderRadius' => array( 'cssVar' => 'tabs-border-radius', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'object' ),
      'shadow' => array( 'cssVar' => 'tabs-border-shadow', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'shadowHover' => array( 'cssVar' => 'tabs-border-shadow-hover', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'tabButtonFontSize' => array( 'cssVar' => 'tabs-button-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'tabButtonFontWeight' => array( 'cssVar' => 'tabs-button-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonFontStyle' => array( 'cssVar' => 'tabs-button-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonTextTransform' => array( 'cssVar' => 'tabs-button-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonTextDecoration' => array( 'cssVar' => 'tabs-button-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonTextAlign' => array( 'cssVar' => 'tabs-button-text-align', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonPadding' => array( 'cssVar' => 'tabs-button-padding', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'tabButtonActiveFontWeight' => array( 'cssVar' => 'tabs-button-active-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonBorderColor' => array( 'cssVar' => 'tabs-button-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'tabButtonActiveBorderColor' => array( 'cssVar' => 'tabs-button-active-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'tabButtonBorderWidth' => array( 'cssVar' => 'tabs-button-border-width', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'tabButtonBorderStyle' => array( 'cssVar' => 'tabs-button-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'tabButtonBorderRadius' => array( 'cssVar' => 'tabs-button-border-radius', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'object' ),
      'tabButtonShadow' => array( 'cssVar' => 'tabs-button-border-shadow', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'tabButtonShadowHover' => array( 'cssVar' => 'tabs-button-border-shadow-hover', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'enableFocusBorder' => array( 'cssVar' => 'tabs-enable-focus-border', 'unit' => null, 'defaultUnit' => null, 'type' => 'boolean' ),
      'tabButtonActiveContentBorderColor' => array( 'cssVar' => 'tabs-button-active-content-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabButtonActiveContentBorderWidth' => array( 'cssVar' => 'tabs-button-active-content-border-width', 'unit' => null, 'defaultUnit' => null, 'type' => 'number' ),
      'tabButtonActiveContentBorderStyle' => array( 'cssVar' => 'tabs-button-active-content-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabListBackgroundColor' => array( 'cssVar' => 'tabs-list-bg', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabsRowBorderColor' => array( 'cssVar' => 'tabs-row-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'tabsRowBorderWidth' => array( 'cssVar' => 'tabs-row-border-width', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'tabsRowBorderStyle' => array( 'cssVar' => 'tabs-row-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'tabsRowSpacing' => array( 'cssVar' => 'tabs-row-spacing', 'unit' => null, 'defaultUnit' => null, 'type' => 'number' ),
      'tabsButtonGap' => array( 'cssVar' => 'tabs-button-gap', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'tabListAlignment' => array( 'cssVar' => 'tabs-list-align', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'enableTabsListContentBorder' => array( 'cssVar' => 'tabs-enable-list-divider-border', 'unit' => null, 'defaultUnit' => null, 'type' => 'boolean' ),
      'tabsListContentBorderColor' => array( 'cssVar' => 'tabs-list-divider-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'tabsListContentBorderWidth' => array( 'cssVar' => 'tabs-list-divider-border-width', 'unit' => null, 'defaultUnit' => null, 'type' => 'number' ),
      'tabsListContentBorderStyle' => array( 'cssVar' => 'tabs-list-divider-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'panelBackgroundColor' => array( 'cssVar' => 'tabs-panel-bg', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'panelBorderColor' => array( 'cssVar' => 'tabs-panel-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'panelBorderWidth' => array( 'cssVar' => 'tabs-panel-border-width', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'number' ),
      'panelBorderStyle' => array( 'cssVar' => 'tabs-panel-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'panelBorderRadius' => array( 'cssVar' => 'tabs-panel-border-radius', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'object' ),
      'showIcon' => array( 'cssVar' => 'tabs-icon-display', 'unit' => null, 'defaultUnit' => null, 'type' => 'boolean' ),
      'iconRotation' => array( 'cssVar' => 'tabs-icon-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconInactiveColor' => array( 'cssVar' => 'tabs-icon-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'iconInactiveRotation' => array( 'cssVar' => 'tabs-icon-initial-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconInactiveSize' => array( 'cssVar' => 'tabs-icon-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveMaxSize' => array( 'cssVar' => 'tabs-icon-max-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveOffsetX' => array( 'cssVar' => 'tabs-icon-offset-x', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveOffsetY' => array( 'cssVar' => 'tabs-icon-offset-y', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveColor' => array( 'cssVar' => 'tabs-icon-active-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'iconActiveRotation' => array( 'cssVar' => 'tabs-icon-active-initial-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconActiveSize' => array( 'cssVar' => 'tabs-icon-active-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveMaxSize' => array( 'cssVar' => 'tabs-icon-active-max-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveOffsetX' => array( 'cssVar' => 'tabs-icon-active-offset-x', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveOffsetY' => array( 'cssVar' => 'tabs-icon-active-offset-y', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
    ),
    'toc' => array(
      'wrapperBackgroundColor' => array( 'cssVar' => 'toc-wrapper-background-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'blockBorderColor' => array( 'cssVar' => 'toc-border-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'h1FontSize' => array( 'cssVar' => 'toc-h1-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'h1FontWeight' => array( 'cssVar' => 'toc-h1-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h1FontStyle' => array( 'cssVar' => 'toc-h1-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h1TextTransform' => array( 'cssVar' => 'toc-h1-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h1TextDecoration' => array( 'cssVar' => 'toc-h1-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h2FontSize' => array( 'cssVar' => 'toc-h2-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'h2FontWeight' => array( 'cssVar' => 'toc-h2-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h2FontStyle' => array( 'cssVar' => 'toc-h2-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h2TextTransform' => array( 'cssVar' => 'toc-h2-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h2TextDecoration' => array( 'cssVar' => 'toc-h2-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h3FontSize' => array( 'cssVar' => 'toc-h3-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'h3FontWeight' => array( 'cssVar' => 'toc-h3-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h3FontStyle' => array( 'cssVar' => 'toc-h3-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h3TextTransform' => array( 'cssVar' => 'toc-h3-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h3TextDecoration' => array( 'cssVar' => 'toc-h3-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h4FontSize' => array( 'cssVar' => 'toc-h4-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'h4FontWeight' => array( 'cssVar' => 'toc-h4-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h4FontStyle' => array( 'cssVar' => 'toc-h4-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h4TextTransform' => array( 'cssVar' => 'toc-h4-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h4TextDecoration' => array( 'cssVar' => 'toc-h4-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h5FontSize' => array( 'cssVar' => 'toc-h5-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'h5FontWeight' => array( 'cssVar' => 'toc-h5-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h5FontStyle' => array( 'cssVar' => 'toc-h5-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h5TextTransform' => array( 'cssVar' => 'toc-h5-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h5TextDecoration' => array( 'cssVar' => 'toc-h5-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h6FontSize' => array( 'cssVar' => 'toc-h6-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'h6FontWeight' => array( 'cssVar' => 'toc-h6-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h6FontStyle' => array( 'cssVar' => 'toc-h6-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h6TextTransform' => array( 'cssVar' => 'toc-h6-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'h6TextDecoration' => array( 'cssVar' => 'toc-h6-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'showIcon' => array( 'cssVar' => 'toc-icon-display', 'unit' => null, 'defaultUnit' => null, 'type' => 'boolean' ),
      'iconRotation' => array( 'cssVar' => 'toc-icon-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconInactiveColor' => array( 'cssVar' => 'toc-icon-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'iconInactiveRotation' => array( 'cssVar' => 'toc-icon-initial-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconInactiveSize' => array( 'cssVar' => 'toc-icon-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveMaxSize' => array( 'cssVar' => 'toc-icon-max-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveOffsetX' => array( 'cssVar' => 'toc-icon-offset-x', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconInactiveOffsetY' => array( 'cssVar' => 'toc-icon-offset-y', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveColor' => array( 'cssVar' => 'toc-icon-active-color', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'iconActiveRotation' => array( 'cssVar' => 'toc-icon-active-initial-rotation', 'unit' => 'deg', 'defaultUnit' => 'deg', 'type' => 'string' ),
      'iconActiveSize' => array( 'cssVar' => 'toc-icon-active-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveMaxSize' => array( 'cssVar' => 'toc-icon-active-max-size', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveOffsetX' => array( 'cssVar' => 'toc-icon-active-offset-x', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'iconActiveOffsetY' => array( 'cssVar' => 'toc-icon-active-offset-y', 'unit' => 'px', 'defaultUnit' => 'px', 'type' => 'string' ),
      'titleFontSize' => array( 'cssVar' => 'toc-title-font-size', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'titleFontWeight' => array( 'cssVar' => 'toc-title-font-weight', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'titleFontStyle' => array( 'cssVar' => 'toc-title-font-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'titleTextTransform' => array( 'cssVar' => 'toc-title-text-transform', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'titleTextDecoration' => array( 'cssVar' => 'toc-title-text-decoration', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'titleAlignment' => array( 'cssVar' => 'toc-title-alignment', 'unit' => null, 'defaultUnit' => null, 'type' => 'string' ),
      'blockBorderWidth' => array( 'cssVar' => 'toc-border-width', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'blockBorderStyle' => array( 'cssVar' => 'toc-border-style', 'unit' => null, 'defaultUnit' => null, 'type' => 'object' ),
      'blockBorderRadius' => array( 'cssVar' => 'toc-border-radius', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'object' ),
      'blockShadow' => array( 'cssVar' => 'toc-border-shadow', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'blockShadowHover' => array( 'cssVar' => 'toc-border-shadow-hover', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'wrapperPadding' => array( 'cssVar' => 'toc-wrapper-padding', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'itemSpacing' => array( 'cssVar' => 'toc-item-spacing', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'levelIndent' => array( 'cssVar' => 'toc-level-indent', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'positionTop' => array( 'cssVar' => 'toc-position-top', 'unit' => null, 'defaultUnit' => 'px', 'type' => 'string' ),
      'zIndex' => array( 'cssVar' => 'toc-z-index', 'unit' => null, 'defaultUnit' => null, 'type' => 'number' ),
    ),
  );

// Return mappings for use in theme-css-generator.php
return $mappings;
