<?php
/**
 * CSS Default Values for Table of Contents Block
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: schemas/toc.json
 * Generated at: 2025-12-29T02:28:32.323Z
 *
 * This file is regenerated on every build. Any manual changes will be lost.
 * To modify this file, update the source schema and run: npm run schema:build
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

return array(
  'includeH1' => 'false',
  'includeH2' => 'true',
  'includeH3' => 'true',
  'includeH4' => 'true',
  'includeH5' => 'true',
  'includeH6' => 'true',
  'includeAccordions' => 'true',
  'includeTabs' => 'true',
  'positionType' => 'normal',
  'smoothScroll' => 'true',
  'scrollOffset' => '0',
  'autoHighlight' => 'true',
  'clickBehavior' => 'navigate',
  'wrapperBackgroundColor' => '#ffffff',
  'titleColor' => '#333333',
  'titleBackgroundColor' => 'transparent',
  'hoverTitleColor' => '#000000',
  'hoverTitleBackgroundColor' => 'transparent',
  'unifiedLinkColors' => 'true',
  'linkColor' => '#0073aa',
  'linkHoverColor' => '#005177',
  'linkActiveColor' => '#005177',
  'linkVisitedColor' => '#0073aa',
  'h1NumberingStyle' => 'decimal',
  'h2NumberingStyle' => 'decimal',
  'h3NumberingStyle' => 'decimal',
  'h4NumberingStyle' => 'decimal',
  'h5NumberingStyle' => 'decimal',
  'h6NumberingStyle' => 'decimal',
  'h1Color' => 'inherit',
  'h1HoverColor' => 'inherit',
  'h1VisitedColor' => 'inherit',
  'h1ActiveColor' => 'inherit',
  'h1FontSize' => '1.5rem',
  'h1FontWeight' => '700',
  'h1FontStyle' => 'normal',
  'h1TextTransform' => 'none',
  'h1TextDecoration' => 'none',
  'h2Color' => 'inherit',
  'h2HoverColor' => 'inherit',
  'h2VisitedColor' => 'inherit',
  'h2ActiveColor' => 'inherit',
  'h2FontSize' => '1.25rem',
  'h2FontWeight' => '600',
  'h2FontStyle' => 'normal',
  'h2TextTransform' => 'none',
  'h2TextDecoration' => 'none',
  'h3Color' => 'inherit',
  'h3HoverColor' => 'inherit',
  'h3VisitedColor' => 'inherit',
  'h3ActiveColor' => 'inherit',
  'h3FontSize' => '1.125rem',
  'h3FontWeight' => '500',
  'h3FontStyle' => 'normal',
  'h3TextTransform' => 'none',
  'h3TextDecoration' => 'none',
  'h4Color' => 'inherit',
  'h4HoverColor' => 'inherit',
  'h4VisitedColor' => 'inherit',
  'h4ActiveColor' => 'inherit',
  'h4FontSize' => '1rem',
  'h4FontWeight' => 'normal',
  'h4FontStyle' => 'normal',
  'h4TextTransform' => 'none',
  'h4TextDecoration' => 'none',
  'h5Color' => 'inherit',
  'h5HoverColor' => 'inherit',
  'h5VisitedColor' => 'inherit',
  'h5ActiveColor' => 'inherit',
  'h5FontSize' => '0.9375rem',
  'h5FontWeight' => 'normal',
  'h5FontStyle' => 'normal',
  'h5TextTransform' => 'none',
  'h5TextDecoration' => 'none',
  'h6Color' => 'inherit',
  'h6HoverColor' => 'inherit',
  'h6VisitedColor' => 'inherit',
  'h6ActiveColor' => 'inherit',
  'h6FontSize' => '0.875rem',
  'h6FontWeight' => 'normal',
  'h6FontStyle' => 'normal',
  'h6TextTransform' => 'none',
  'h6TextDecoration' => 'none',
  'showIcon' => 'true',
  'iconPosition' => 'right',
  'iconSize' => '1.25rem',
  'iconTypeClosed' => '▾',
  'iconTypeOpen' => 'none',
  'iconRotation' => '180deg',
  'iconColor' => '#666666',
  'titleFontSize' => '1.25rem',
  'titleFontWeight' => '700',
  'titleFontStyle' => 'normal',
  'titleTextTransform' => 'none',
  'titleTextDecoration' => 'none',
  'titleAlignment' => 'left',
  'blockBorderWidth' => '1px',
  'blockShadow' => 'none',
  'blockShadowHover' => 'none',
  'wrapperPadding' => '1.25rem',
  'itemSpacing' => '0.5rem',
  'enableHierarchicalIndent' => 'true',
  'levelIndent' => '1.25rem',
  'positionTop' => '6.25rem',
  'zIndex' => '100',
  'positionHorizontalSide' => 'right',
  'positionHorizontalOffset' => '1.25rem',
);
