/**
 * TOC Block - Save Component
 *
 * Generates the static HTML output for the frontend.
 * Applies theme class names and only outputs inline CSS for explicit customizations.
 * Uses hybrid Tier 2 CSS approach for optimal performance.
 *
 * The actual heading detection happens via JavaScript on the frontend.
 *
 * Note: Headings are detected client-side to ensure TOC updates
 * if content changes after initial save.
 *
 * @package
 * @since 1.0.0
 */

import { useBlockProps } from '@wordpress/block-editor';
import { getAllEffectiveValues } from '../../../shared/src/theme-system/cascade-resolver';
import { getCSSDefault } from '../../../shared/src/utils/css-parser';

/**
 * Save Component
 * @param root0
 * @param root0.attributes
 */
export default function save( { attributes } ) {
	const {
		tocId,
		showTitle,
		titleText,
		isCollapsible,
		initiallyCollapsed,
		filterMode,
		includeLevels,
		includeClasses,
		excludeLevels,
		excludeClasses,
		depthLimit,
		numberingStyle,
		smoothScroll,
		scrollOffset,
		autoHighlight,
		positionType,
		clickBehavior,
	} = attributes;

	// Get CSS defaults
	const cssDefaults = getCSSDefault( 'toc' ) || {};

	// Get effective values for display purposes (title rendering, etc.)
	const effectiveValues = getAllEffectiveValues( attributes, null, cssDefaults );

	// Build inline styles ONLY for explicit customizations (Tier 3)
	// Theme values (Tier 2) are applied via CSS classes generated by PHP
	const customizationStyles = buildCustomizationStyles( attributes );

	// Data attributes for frontend JS
	const dataAttributes = {
		'data-toc-id': tocId,
		'data-filter-mode': filterMode,
		'data-include-levels': includeLevels.join( ',' ),
		'data-include-classes': includeClasses,
		'data-exclude-levels': excludeLevels.join( ',' ),
		'data-exclude-classes': excludeClasses,
		'data-depth-limit': depthLimit || 0,
		'data-numbering-style': numberingStyle,
		'data-smooth-scroll': smoothScroll,
		'data-scroll-offset': scrollOffset,
		'data-auto-highlight': autoHighlight,
		'data-collapsible': isCollapsible,
		'data-initially-collapsed': initiallyCollapsed,
		'data-position-type': positionType,
		'data-click-behavior': clickBehavior || 'navigate',
	};

	// Build class names - add theme class if using a theme
	const classNames = [ 'wp-block-custom-toc', `toc-position-${ positionType }` ];
	if ( attributes.currentTheme ) {
		// Sanitize theme ID for CSS class (alphanumeric and hyphens only)
		const safeThemeId = attributes.currentTheme.replace( /[^a-zA-Z0-9\-]/g, '' );
		classNames.push( `toc-theme-${ safeThemeId }` );
	}

	// Block props
	const blockProps = useBlockProps.save( {
		className: classNames.join( ' ' ),
		// Only add inline styles if there are customizations
		...( Object.keys( customizationStyles ).length > 0 && { style: customizationStyles } ),
		...dataAttributes,
	} );

	// Collapse button ID
	const buttonId = `toc-toggle-${ tocId }`;
	const contentId = `toc-content-${ tocId }`;

	return (
		<div { ...blockProps }>
			{ showTitle && ! isCollapsible && (
				<div
					className="toc-title"
					style={ {
						fontSize: `${ effectiveValues.titleFontSize || 20 }px`,
						fontWeight: effectiveValues.titleFontWeight || '700',
						color: effectiveValues.titleColor || '#333333',
						backgroundColor: effectiveValues.titleBackgroundColor || 'transparent',
						textAlign: effectiveValues.titleAlignment || 'left',
						padding: `${ effectiveValues.titlePadding || 12 }px`,
					} }
				>
					{ titleText }
				</div>
			) }

			{ showTitle && isCollapsible && (
				<button
					id={ buttonId }
					className="toc-title toc-toggle-button"
					aria-expanded={ ! initiallyCollapsed }
					aria-controls={ contentId }
					type="button"
					style={ {
						fontSize: `${ effectiveValues.titleFontSize || 20 }px`,
						fontWeight: effectiveValues.titleFontWeight || '700',
						color: effectiveValues.titleColor || '#333333',
						backgroundColor: effectiveValues.titleBackgroundColor || 'transparent',
						textAlign: effectiveValues.titleAlignment || 'left',
						padding: `${ effectiveValues.titlePadding || 12 }px`,
						border: 'none',
						width: '100%',
						cursor: 'pointer',
						display: 'flex',
						justifyContent: 'space-between',
						alignItems: 'center',
					} }
				>
					<span>{ titleText }</span>
					<span
						className="toc-collapse-icon"
						aria-hidden="true"
						style={ {
							fontSize: `${ effectiveValues.collapseIconSize || 20 }px`,
							color: effectiveValues.collapseIconColor || '#666666',
						} }
					>
						▾
					</span>
				</button>
			) }

			{ ! showTitle && isCollapsible && (
				<button
					id={ buttonId }
					className="toc-toggle-button toc-icon-only"
					aria-expanded={ ! initiallyCollapsed }
					aria-controls={ contentId }
					aria-label="Toggle Table of Contents"
					type="button"
					style={ {
						position: 'absolute',
						top: '10px',
						right: '10px',
						background: 'none',
						border: 'none',
						cursor: 'pointer',
						fontSize: `${ effectiveValues.collapseIconSize || 20 }px`,
						color: effectiveValues.collapseIconColor || '#666666',
					} }
				>
					▾
				</button>
			) }

			<nav
				id={ contentId }
				className="toc-content"
				aria-label={ titleText || 'Table of Contents' }
				style={ {
					display: isCollapsible && initiallyCollapsed ? 'none' : 'block',
				} }
			>
				<ul
					className={ `toc-list numbering-${ numberingStyle }` }
					style={ {
						listStyleType: numberingStyle === 'none' ? 'disc' : 'none',
						paddingLeft: `${ effectiveValues.listPaddingLeft || 24 }px`,
						margin: 0,
					} }
				>
					<li className="toc-placeholder">Loading table of contents...</li>
				</ul>
			</nav>
		</div>
	);
}

/**
 * Build inline CSS custom properties ONLY for explicit customizations (Tier 3)
 * Only outputs attributes that are explicitly defined (not null/undefined)
 * Theme values (Tier 2) are applied via CSS classes generated by PHP
 * CSS defaults (Tier 1) are in the stylesheet
 *
 * @param attributes Block attributes
 */
function buildCustomizationStyles( attributes ) {
	const styles = {};

	// Helper to add style if attribute is explicitly defined
	const addIfDefined = ( attrName, cssVar, formatter ) => {
		if ( attributes[ attrName ] !== null && attributes[ attrName ] !== undefined ) {
			styles[ cssVar ] = formatter ? formatter( attributes[ attrName ] ) : attributes[ attrName ];
		}
	};

	// Wrapper colors
	addIfDefined( 'wrapperBackgroundColor', '--toc-wrapper-background-color' );
	addIfDefined( 'wrapperBorderColor', '--toc-wrapper-border-color' );

	// Link colors
	addIfDefined( 'linkColor', '--toc-link-color' );
	addIfDefined( 'linkHoverColor', '--toc-link-hover-color' );
	addIfDefined( 'linkVisitedColor', '--toc-link-visited-color' );
	addIfDefined( 'linkActiveColor', '--toc-link-active-color' );

	// Numbering color
	addIfDefined( 'numberingColor', '--toc-numbering-color' );

	// Level colors
	addIfDefined( 'level1Color', '--toc-level1-color' );
	addIfDefined( 'level2Color', '--toc-level2-color' );
	addIfDefined( 'level3PlusColor', '--toc-level3-plus-color' );

	// Level 1 typography
	addIfDefined( 'level1FontSize', '--toc-level1-font-size', ( val ) => `${ val }px` );
	addIfDefined( 'level1FontWeight', '--toc-level1-font-weight' );
	addIfDefined( 'level1FontStyle', '--toc-level1-font-style' );
	addIfDefined( 'level1TextTransform', '--toc-level1-text-transform' );
	addIfDefined( 'level1TextDecoration', '--toc-level1-text-decoration' );

	// Level 2 typography
	addIfDefined( 'level2FontSize', '--toc-level2-font-size', ( val ) => `${ val }px` );
	addIfDefined( 'level2FontWeight', '--toc-level2-font-weight' );
	addIfDefined( 'level2FontStyle', '--toc-level2-font-style' );
	addIfDefined( 'level2TextTransform', '--toc-level2-text-transform' );
	addIfDefined( 'level2TextDecoration', '--toc-level2-text-decoration' );

	// Level 3+ typography
	addIfDefined( 'level3PlusFontSize', '--toc-level3-plus-font-size', ( val ) => `${ val }px` );
	addIfDefined( 'level3PlusFontWeight', '--toc-level3-plus-font-weight' );
	addIfDefined( 'level3PlusFontStyle', '--toc-level3-plus-font-style' );
	addIfDefined( 'level3PlusTextTransform', '--toc-level3-plus-text-transform' );
	addIfDefined( 'level3PlusTextDecoration', '--toc-level3-plus-text-decoration' );

	// Border
	addIfDefined( 'wrapperBorderWidth', '--toc-border-width', ( val ) => `${ val }px` );
	addIfDefined( 'wrapperBorderStyle', '--toc-border-style' );
	addIfDefined( 'wrapperBorderRadius', '--toc-border-radius', ( val ) => `${ val }px` );

	// Padding & Spacing
	addIfDefined( 'wrapperPadding', '--toc-wrapper-padding', ( val ) => `${ val }px` );
	addIfDefined( 'itemSpacing', '--toc-item-spacing', ( val ) => `${ val }px` );
	addIfDefined( 'levelIndent', '--toc-level-indent', ( val ) => `${ val }px` );

	// Position
	addIfDefined( 'positionTop', '--toc-position-top', ( val ) => `${ val }px` );
	addIfDefined( 'zIndex', '--toc-z-index' );

	// Shadow
	addIfDefined( 'wrapperShadow', '--toc-wrapper-shadow' );

	return styles;
}
