/**
 * Tabs Block - Save Component
 *
 * Renders the frontend HTML structure with proper ARIA attributes for tabs.
 * Applies theme class names and only outputs inline CSS for explicit customizations.
 * Uses hybrid Tier 2 CSS approach for optimal performance.
 * Supports horizontal/vertical orientation and responsive fallback.
 *
 * @package
 * @since 1.0.0
 */

import { useBlockProps, InnerBlocks } from '@wordpress/block-editor';
import { getAllEffectiveValues } from '@shared';

/**
 * Tabs Save Component
 *
 * @param {Object} props            Block props
 * @param {Object} props.attributes Block attributes
 * @return {JSX.Element} Save component
 */
export default function Save( { attributes } ) {
	// Get CSS defaults (will be available via wp_localize_script in frontend)
	const cssDefaults = window.tabsDefaults || {};

	// Get effective values for display purposes (icon rendering, etc.)
	const effectiveValues = getAllEffectiveValues(
		attributes,
		{}, // Themes are resolved server-side via CSS classes
		cssDefaults,
		'tabs'
	);

	/**
	 * Build inline CSS variables ONLY for explicit customizations (Tier 3)
	 * Theme values (Tier 2) are applied via CSS classes generated by PHP
	 * CSS defaults (Tier 1) are in the stylesheet
	 */
	const getCustomizationStyles = () => {
		const styles = {};

		// Helper to add style if attribute is explicitly defined
		const addIfDefined = ( attrName, cssVar, formatter ) => {
			if ( attributes[ attrName ] !== null && attributes[ attrName ] !== undefined ) {
				styles[ cssVar ] = formatter ? formatter( attributes[ attrName ] ) : attributes[ attrName ];
			}
		};

		// Tab Button (title colors from ColorPanel)
		addIfDefined( 'titleColor', '--tab-button-color' );
		addIfDefined( 'titleBackgroundColor', '--tab-button-bg' );
		addIfDefined( 'hoverTitleColor', '--tab-button-hover-color' );
		addIfDefined( 'hoverTitleBackgroundColor', '--tab-button-hover-bg' );
		addIfDefined( 'activeTitleColor', '--tab-button-active-color' );
		addIfDefined( 'activeTitleBackgroundColor', '--tab-button-active-bg' );

		// Tab Button Typography (from TypographyPanel)
		addIfDefined( 'titleFontSize', '--tab-button-font-size', ( val ) => `${ val }px` );
		addIfDefined( 'titleFontWeight', '--tab-button-font-weight' );
		addIfDefined( 'titleFontStyle', '--tab-button-font-style' );
		addIfDefined( 'titleTextTransform', '--tab-button-text-transform' );
		addIfDefined( 'titleTextDecoration', '--tab-button-text-decoration' );
		addIfDefined( 'titleAlignment', '--tab-button-text-align' );

		// Tab Panel (content colors from ColorPanel)
		addIfDefined( 'contentBackgroundColor', '--panel-bg' );
		addIfDefined( 'contentColor', '--panel-color' );

		// Border (from BorderPanel - using tab-specific attributes)
		addIfDefined( 'tabBorderColor', '--tab-button-border-color' );
		addIfDefined( 'tabBorderThickness', '--tab-button-border-width', ( val ) => `${ val }px` );
		addIfDefined( 'tabBorderStyle', '--tab-button-border-style' );
		addIfDefined( 'tabShadow', '--tabs-container-shadow' );
		addIfDefined( 'dividerColor', '--divider-color' );
		addIfDefined( 'dividerThickness', '--divider-width', ( val ) => `${ val }px` );
		addIfDefined( 'dividerStyle', '--divider-style' );

		// Border Radius (from BorderPanel)
		if ( attributes.tabBorderRadius ) {
			const br = attributes.tabBorderRadius;
			styles[ '--tab-button-border-radius' ] = `${ br.topLeft }px ${ br.topRight }px ${ br.bottomRight }px ${ br.bottomLeft }px`;
		}

		// Icon (from IconPanel)
		addIfDefined( 'iconSize', '--icon-size', ( val ) => `${ val }px` );
		addIfDefined( 'iconColor', '--icon-color' );

		// Responsive breakpoint (from Tab Settings panel)
		if ( attributes.responsiveBreakpoint ) {
			styles[ '--responsive-breakpoint' ] = `${ attributes.responsiveBreakpoint }px`;
		}

		return styles;
	};

	const customizationStyles = getCustomizationStyles();

	/**
	 * Render icon based on settings
	 */
	const renderIcon = () => {
		if ( ! effectiveValues.showIcon ) {
			return null;
		}

		const iconContent = effectiveValues.iconTypeClosed || '📄';
		const isImage = iconContent.startsWith( 'http' );

		if ( isImage ) {
			return (
				<img
					src={ iconContent }
					alt=""
					aria-hidden="true"
					className="tab-icon tab-icon-image"
				/>
			);
		}

		return (
			<span className="tab-icon" aria-hidden="true">
				{ iconContent }
			</span>
		);
	};

	// Build class names - add theme class if using a theme
	const classNames = [ 'wp-block-tabs' ];
	if ( attributes.currentTheme ) {
		// Sanitize theme ID for CSS class (alphanumeric and hyphens only)
		const safeThemeId = attributes.currentTheme.replace( /[^a-zA-Z0-9\-]/g, '' );
		classNames.push( `tabs-theme-${ safeThemeId }` );
	}
	if ( attributes.enableResponsiveFallback ) {
		classNames.push( 'responsive-accordion' );
	}

	const blockProps = useBlockProps.save( {
		className: classNames.join( ' ' ),
		'data-orientation': attributes.orientation || 'horizontal',
		'data-activation-mode': attributes.activationMode || 'auto',
		'data-breakpoint': attributes.responsiveBreakpoint || 768,
		'data-responsive-fallback': attributes.enableResponsiveFallback || true,
		// Only add inline styles if there are customizations
		...( Object.keys( customizationStyles ).length > 0 && { style: customizationStyles } ),
	} );

	return (
		<div { ...blockProps }>
			{ /* Tab List - populated by frontend JavaScript */ }
			<div
				className="tabs-list"
				role="tablist"
				aria-orientation={ attributes.orientation || 'horizontal' }
				data-current-tab={ attributes.currentTab || 0 }
			></div>

			{ /* Tab Panels */ }
			<div className="tabs-panels">
				<InnerBlocks.Content />
			</div>
		</div>
	);
}
