/**
 * Zod Validation Schema for Tabs Block
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: schemas/tabs.json
 * Generated at: 2025-11-22T15:43:23.194Z
 *
 * This file is regenerated on every build. Any manual changes will be lost.
 * To modify this file, update the source schema and run: npm run schema:build
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

import { z } from 'zod';

/**
 * Validation schema for Tabs theme values
 */
export const tabsThemeSchema = z.object({
  titleColor: z.string(),
  titleBackgroundColor: z.string(),
  hoverTitleColor: z.string(),
  hoverTitleBackgroundColor: z.string(),
  activeTitleColor: z.string().optional(),
  activeTitleBackgroundColor: z.string().optional(),
  tabButtonActiveColor: z.string(),
  tabButtonActiveBackground: z.string(),
  tabButtonActiveBorderColor: z.string(),
  tabButtonActiveBorderBottomColor: z.string(),
  contentColor: z.string().optional(),
  contentBackgroundColor: z.string().optional(),
  panelBackground: z.string(),
  panelColor: z.string(),
  tabListBackground: z.string(),
  tabBorderColor: z.string().optional(),
  containerBorderColor: z.string(),
  panelBorderColor: z.string(),
  tabListBorderBottomColor: z.string(),
  dividerColor: z.string().optional(),
  borderColor: z.string().optional(),
  accordionBorderColor: z.string().optional(),
  dividerBorderColor: z.string().optional(),
  iconColor: z.string(),
  titleFontSize: z.number(),
  titleFontWeight: z.string(),
  titleFontFamily: z.string().optional(),
  titleLineHeight: z.number().optional(),
  titleFontStyle: z.string(),
  titleTextTransform: z.string(),
  titleTextDecoration: z.string(),
  titleAlignment: z.string(),
  contentFontSize: z.number().optional(),
  contentFontWeight: z.string().optional(),
  contentFontFamily: z.string().optional(),
  contentLineHeight: z.number().optional(),
  contentFontStyle: z.string().optional(),
  contentTextTransform: z.string().optional(),
  contentTextDecoration: z.string().optional(),
  panelFontSize: z.number(),
  panelLineHeight: z.number(),
  verticalTabButtonTextAlign: z.string(),
  tabBorderThickness: z.number().optional(),
  tabBorderStyle: z.string().optional(),
  tabBorderRadius: z.record(z.any()),
  tabShadow: z.string().optional(),
  tabButtonBorderRadius: z.record(z.any()).optional(),
  containerBorderWidth: z.number(),
  containerBorderStyle: z.string(),
  containerBorderRadius: z.record(z.any()),
  containerShadow: z.string(),
  panelBorderWidth: z.number(),
  panelBorderStyle: z.string(),
  panelBorderRadius: z.number(),
  tabListBorderBottomWidth: z.number(),
  tabListBorderBottomStyle: z.string(),
  dividerThickness: z.number().optional(),
  dividerStyle: z.string().optional(),
  accordionBorderThickness: z.number().optional(),
  accordionBorderStyle: z.string().optional(),
  accordionBorderRadius: z.record(z.any()).optional(),
  accordionShadow: z.string().optional(),
  borderWidth: z.string().optional(),
  borderRadius: z.string().optional(),
  dividerBorderThickness: z.number().optional(),
  dividerBorderStyle: z.string().optional(),
  titlePadding: z.record(z.any()),
  contentPadding: z.record(z.any()).optional(),
  panelPadding: z.record(z.any()),
  tabListPadding: z.record(z.any()),
  tabListGap: z.number(),
  tabsAlignment: z.string(),
  verticalTabListWidth: z.number(),
  accordionMarginBottom: z.number().optional(),
  itemSpacing: z.number().optional(),
  showIcon: z.boolean(),
  iconPosition: z.string(),
  iconSize: z.number(),
  iconTypeClosed: z.string(),
  iconTypeOpen: z.string(),
  iconRotation: z.number(),
});

/**
 * Validation schema for all Tabs block attributes
 */
export const tabsAttributesSchema = z.object({
  uniqueId: z.string(),
  blockId: z.string(),
  currentTheme: z.string(),
  tabs: z.array(z.any()),
  orientation: z.string(),
  activationMode: z.string(),
  currentTab: z.number(),
  responsiveBreakpoint: z.number(),
  enableResponsiveFallback: z.boolean(),
  headingLevel: z.string(),
  useHeadingStyles: z.boolean(),
  initiallyOpen: z.boolean(),
  title: z.string(),
  content: z.string(),
  accordionId: z.string(),
  titleColor: z.string(),
  titleBackgroundColor: z.string(),
  hoverTitleColor: z.string(),
  hoverTitleBackgroundColor: z.string(),
  activeTitleColor: z.string().optional(),
  activeTitleBackgroundColor: z.string().optional(),
  tabButtonActiveColor: z.string(),
  tabButtonActiveBackground: z.string(),
  tabButtonActiveBorderColor: z.string(),
  tabButtonActiveBorderBottomColor: z.string(),
  contentColor: z.string().optional(),
  contentBackgroundColor: z.string().optional(),
  panelBackground: z.string(),
  panelColor: z.string(),
  tabListBackground: z.string(),
  tabBorderColor: z.string().optional(),
  containerBorderColor: z.string(),
  panelBorderColor: z.string(),
  tabListBorderBottomColor: z.string(),
  dividerColor: z.string().optional(),
  borderColor: z.string().optional(),
  accordionBorderColor: z.string().optional(),
  dividerBorderColor: z.string().optional(),
  iconColor: z.string(),
  titleFontSize: z.number(),
  titleFontWeight: z.string(),
  titleFontFamily: z.string().optional(),
  titleLineHeight: z.number().optional(),
  titleFontStyle: z.string(),
  titleTextTransform: z.string(),
  titleTextDecoration: z.string(),
  titleAlignment: z.string(),
  contentFontSize: z.number().optional(),
  contentFontWeight: z.string().optional(),
  contentFontFamily: z.string().optional(),
  contentLineHeight: z.number().optional(),
  contentFontStyle: z.string().optional(),
  contentTextTransform: z.string().optional(),
  contentTextDecoration: z.string().optional(),
  panelFontSize: z.number(),
  panelLineHeight: z.number(),
  verticalTabButtonTextAlign: z.string(),
  tabBorderThickness: z.number().optional(),
  tabBorderStyle: z.string().optional(),
  tabBorderRadius: z.record(z.any()),
  tabShadow: z.string().optional(),
  tabButtonBorderRadius: z.record(z.any()).optional(),
  containerBorderWidth: z.number(),
  containerBorderStyle: z.string(),
  containerBorderRadius: z.record(z.any()),
  containerShadow: z.string(),
  panelBorderWidth: z.number(),
  panelBorderStyle: z.string(),
  panelBorderRadius: z.number(),
  tabListBorderBottomWidth: z.number(),
  tabListBorderBottomStyle: z.string(),
  dividerThickness: z.number().optional(),
  dividerStyle: z.string().optional(),
  accordionBorderThickness: z.number().optional(),
  accordionBorderStyle: z.string().optional(),
  accordionBorderRadius: z.record(z.any()).optional(),
  accordionShadow: z.string().optional(),
  borderWidth: z.string().optional(),
  borderRadius: z.string().optional(),
  dividerBorderThickness: z.number().optional(),
  dividerBorderStyle: z.string().optional(),
  titlePadding: z.record(z.any()),
  contentPadding: z.record(z.any()).optional(),
  panelPadding: z.record(z.any()),
  tabListPadding: z.record(z.any()),
  tabListGap: z.number(),
  tabsAlignment: z.string(),
  verticalTabListWidth: z.number(),
  accordionMarginBottom: z.number().optional(),
  itemSpacing: z.number().optional(),
  showIcon: z.boolean(),
  iconPosition: z.string(),
  iconSize: z.number(),
  iconTypeClosed: z.string(),
  iconTypeOpen: z.string(),
  iconRotation: z.number(),
});

// Type inference exports
export type TabsTheme = z.infer<typeof tabsThemeSchema>;
export type TabsAttributes = z.infer<typeof tabsAttributesSchema>;
