/**
 * Block Attributes for Table of Contents
 *
 * AUTO-GENERATED - DO NOT EDIT MANUALLY
 * Generated from: schemas/generated/toc.json
 * Generated at: 2026-01-19T16:38:17.044Z
 *
 * This file contains atomic, flat attributes in kebab-case format.
 * Each attribute represents a single configurable property.
 *
 * Special Attributes:
 * - currentTheme: Currently applied theme name
 * - customizations: Per-block customizations (overrides theme)
 * - tocId: Unique identifier for this table of contents
 *
 * All other attributes are auto-generated from the comprehensive schema.
 * To modify attributes, edit schemas/blocks/toc.json and rebuild.
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

export const tocAttributes = {
	customizations: { type: 'object', default: {} },
	'autoHighlight': { type: 'boolean', default: true },
	'blockBorderColor': { type: 'object', default: {"top":"#dddddd","right":"#dddddd","bottom":"#dddddd","left":"#dddddd"} },
	'blockBorderRadius': { type: 'object', default: {"topLeft":4,"topRight":4,"bottomRight":4,"bottomLeft":4,"unit":"px"} },
	'blockBorderStyle': { type: 'object', default: {"top":"solid","right":"solid","bottom":"solid","left":"solid"} },
	'blockBorderWidth': { type: 'string', default: "1" },
	'blockShadow': { type: 'string', default: "none" },
	'blockShadowHover': { type: 'string', default: "none" },
	'clickBehavior': { type: 'string', default: "navigate" },
	'currentTheme': { type: 'string', default: "" },
	'deletedHeadingIds': { type: 'array', default: [] },
	'enableHierarchicalIndent': { type: 'boolean', default: true },
	'excludeClasses': { type: 'string', default: "" },
	'excludeLevels': { type: 'array', default: [] },
	'filterMode': { type: 'string', default: "Include all headings" },
	'h1-color-text': { type: 'string', default: "inherit" },
	'h1-color-text-active': { type: 'string', default: "inherit" },
	'h1-color-text-hover': { type: 'string', default: "inherit" },
	'h1-color-text-visited': { type: 'string', default: "inherit" },
	'h1FontSize': { type: 'string', default: "1.5rem" },
	'h1FontStyle': { type: 'string', default: "normal" },
	'h1FontWeight': { type: 'string', default: "700" },
	'h1NumberingStyle': { type: 'string', default: "decimal" },
	'h1TextDecoration': { type: 'string', default: "none" },
	'h1TextTransform': { type: 'string', default: "none" },
	'h2-color-text': { type: 'string', default: "inherit" },
	'h2-color-text-active': { type: 'string', default: "inherit" },
	'h2-color-text-hover': { type: 'string', default: "inherit" },
	'h2-color-text-visited': { type: 'string', default: "inherit" },
	'h2FontSize': { type: 'string', default: "1.25rem" },
	'h2FontStyle': { type: 'string', default: "normal" },
	'h2FontWeight': { type: 'string', default: "600" },
	'h2NumberingStyle': { type: 'string', default: "decimal" },
	'h2TextDecoration': { type: 'string', default: "none" },
	'h2TextTransform': { type: 'string', default: "none" },
	'h3-color-text': { type: 'string', default: "inherit" },
	'h3-color-text-active': { type: 'string', default: "inherit" },
	'h3-color-text-hover': { type: 'string', default: "inherit" },
	'h3-color-text-visited': { type: 'string', default: "inherit" },
	'h3FontSize': { type: 'string', default: "1.125rem" },
	'h3FontStyle': { type: 'string', default: "normal" },
	'h3FontWeight': { type: 'string', default: "500" },
	'h3NumberingStyle': { type: 'string', default: "decimal" },
	'h3TextDecoration': { type: 'string', default: "none" },
	'h3TextTransform': { type: 'string', default: "none" },
	'h4-color-text': { type: 'string', default: "inherit" },
	'h4-color-text-active': { type: 'string', default: "inherit" },
	'h4-color-text-hover': { type: 'string', default: "inherit" },
	'h4-color-text-visited': { type: 'string', default: "inherit" },
	'h4FontSize': { type: 'string', default: "1rem" },
	'h4FontStyle': { type: 'string', default: "normal" },
	'h4FontWeight': { type: 'string', default: "normal" },
	'h4NumberingStyle': { type: 'string', default: "decimal" },
	'h4TextDecoration': { type: 'string', default: "none" },
	'h4TextTransform': { type: 'string', default: "none" },
	'h5-color-text': { type: 'string', default: "inherit" },
	'h5-color-text-active': { type: 'string', default: "inherit" },
	'h5-color-text-hover': { type: 'string', default: "inherit" },
	'h5-color-text-visited': { type: 'string', default: "inherit" },
	'h5FontSize': { type: 'string', default: "0.9375rem" },
	'h5FontStyle': { type: 'string', default: "normal" },
	'h5FontWeight': { type: 'string', default: "normal" },
	'h5NumberingStyle': { type: 'string', default: "decimal" },
	'h5TextDecoration': { type: 'string', default: "none" },
	'h5TextTransform': { type: 'string', default: "none" },
	'h6-color-text': { type: 'string', default: "inherit" },
	'h6-color-text-active': { type: 'string', default: "inherit" },
	'h6-color-text-hover': { type: 'string', default: "inherit" },
	'h6-color-text-visited': { type: 'string', default: "inherit" },
	'h6FontSize': { type: 'string', default: "0.875rem" },
	'h6FontStyle': { type: 'string', default: "normal" },
	'h6FontWeight': { type: 'string', default: "normal" },
	'h6NumberingStyle': { type: 'string', default: "decimal" },
	'h6TextDecoration': { type: 'string', default: "none" },
	'h6TextTransform': { type: 'string', default: "none" },
	'includeAccordions': { type: 'boolean', default: true },
	'includeClasses': { type: 'string', default: "" },
	'includeH1': { type: 'boolean', default: false },
	'includeH2': { type: 'boolean', default: true },
	'includeH3': { type: 'boolean', default: true },
	'includeH4': { type: 'boolean', default: true },
	'includeH5': { type: 'boolean', default: true },
	'includeH6': { type: 'boolean', default: true },
	'includeLevels': { type: 'array', default: [2,3,4,5,6] },
	'includeTabs': { type: 'boolean', default: true },
	'initiallyCollapsed': { type: 'boolean', default: false },
	'isCollapsible': { type: 'boolean', default: true },
	'itemSpacing': { type: 'string', default: "0.5rem" },
	'levelIndent': { type: 'string', default: "1.25rem" },
	'link-color-text': { type: 'string', default: "#0073aa" },
	'link-color-text-active': { type: 'string', default: "#005177" },
	'link-color-text-hover': { type: 'string', default: "#005177" },
	'link-color-text-visited': { type: 'string', default: "#0073aa" },
	'positionHorizontalOffset': { type: 'string', default: "1.25rem" },
	'positionHorizontalSide': { type: 'string', default: "right" },
	'positionTop': { type: 'string', default: "6.25rem" },
	'positionType': { type: 'string', default: "normal" },
	'scrollOffset': { type: 'number', default: 0 },
	'showTitle': { type: 'boolean', default: true },
	'smoothScroll': { type: 'boolean', default: true },
	'title-color-background': { type: 'string', default: "transparent" },
	'title-color-background-hover': { type: 'string', default: "transparent" },
	'title-color-text': { type: 'string', default: "#333333" },
	'title-color-text-hover': { type: 'string', default: "#000000" },
	'titleAlignment': { type: 'string', default: "left" },
	'titleFontSize': { type: 'string', default: "1.25rem" },
	'titleFontStyle': { type: 'string', default: "normal" },
	'titleFontWeight': { type: 'string', default: "700" },
	'titleText': { type: 'string', default: "Table of Contents" },
	'titleTextDecoration': { type: 'string', default: "none" },
	'titleTextTransform': { type: 'string', default: "none" },
	'toc-icon-animation-rotation': { type: 'string', default: "180deg" },
	'toc-icon-color': { type: 'string', default: "#333333" },
	'toc-icon-color-is-open': { type: 'string', default: "#333333" },
	'toc-icon-initial-rotation': { type: 'string', default: "0deg" },
	'toc-icon-initial-rotation-is-open': { type: 'string', default: "0deg" },
	'toc-icon-max-size': { type: 'string', default: "24px" },
	'toc-icon-max-size-is-open': { type: 'string', default: "24px" },
	'toc-icon-offset-x': { type: 'string', default: "0px" },
	'toc-icon-offset-x-is-open': { type: 'string', default: "0px" },
	'toc-icon-offset-y': { type: 'string', default: "0px" },
	'toc-icon-offset-y-is-open': { type: 'string', default: "0px" },
	'toc-icon-position': { type: 'string', default: "right" },
	'toc-icon-show': { type: 'boolean', default: true },
	'toc-icon-size': { type: 'string', default: "16px" },
	'toc-icon-size-is-open': { type: 'string', default: "16px" },
	'toc-icon-source': { type: 'object', default: {"kind":"char","value":"▾"} },
	'toc-icon-source-is-open': { type: 'object', default: {"kind":"char","value":"▾"} },
	'toc-icon-transform': { type: 'string', default: undefined },
	'toc-icon-transform-is-open': { type: 'string', default: undefined },
	'toc-icon-use-different-icons': { type: 'boolean', default: false },
	'tocHorizontalAlign': { type: 'string', default: "center" },
	'tocId': { type: 'string', default: "" },
	'tocItems': { type: 'array', default: [] },
	'tocWidth': { type: 'string', default: "100%" },
	'unifiedLinkColors': { type: 'boolean', default: true },
	'wrapperBackgroundColor': { type: 'string', default: "#ffffff" },
	'wrapperPadding': { type: 'string', default: "1.25rem" },
	'zIndex': { type: 'number', default: 100 },
};

export default tocAttributes;
