/**
 * Utility: getCustomizationStyles
 *
 * Builds inline CSS variables ONLY for explicit customizations (Tier 3).
 * Theme values (Tier 2) are applied via CSS classes generated by PHP.
 * CSS defaults (Tier 1) are in the stylesheet.
 *
 * Centralizes duplicated customization style logic from all block save.js files.
 *
 * @param {Object} attributes - Block attributes containing customizations
 * @param {string} blockType - Block type identifier ('accordion', 'tabs', 'toc')
 * @return {Object} CSS custom properties object for inline styles
 *
 * @example
 * ```javascript
 * import { getCustomizationStyles } from '@shared';
 *
 * function Save({ attributes }) {
 *     const customizationStyles = getCustomizationStyles(attributes, 'accordion');
 *
 *     return (
 *         <div style={customizationStyles}>
 *             ...
 *         </div>
 *     );
 * }
 * ```
 *
 * @package
 * @since 1.0.0
 */

import { getCssVarName, formatCssValue } from '../config/css-var-mappings-generated';

/**
 * Build inline CSS variables for customizations
 *
 * @param {Object} attributes - Block attributes
 * @param {string} blockType - Block type ('accordion', 'tabs', 'toc')
 * @return {Object} CSS custom properties object
 */
export function getCustomizationStyles( attributes, blockType ) {
	const styles = {};

	// Get customizations (deltas from expected values, calculated in edit.js)
	const customizations = attributes.customizations || {};

	// Process each customization using schema-generated mappings
	Object.entries( customizations ).forEach( ( [ attrName, value ] ) => {
		if ( value === null || value === undefined ) {
			return;
		}

		// Get CSS variable name from generated mappings
		const cssVar = getCssVarName( attrName, blockType );
		if ( ! cssVar ) {
			return; // Attribute not mapped to a CSS variable
		}

		// Format value with proper unit from generated mappings
		const formattedValue = formatCssValue( attrName, value, blockType );
		if ( formattedValue !== null ) {
			styles[ cssVar ] = formattedValue;
		}
	} );

	return styles;
}

/**
 * Build inline CSS variables for tabs with toggle support
 *
 * Tabs block has special toggle attributes (enableFocusBorder, enableDividerBorder)
 * that control whether certain CSS variables should be output.
 *
 * @param {Object} attributes - Block attributes
 * @return {Object} CSS custom properties object
 */
export function getTabsCustomizationStyles( attributes ) {
	const styles = {};

	// Define which attributes are controlled by feature toggles
	const toggledAttributes = {
		focusBorderColor: 'enableFocusBorder',
		focusBorderColorActive: 'enableFocusBorder',
		focusBorderWidth: 'enableFocusBorder',
		focusBorderStyle: 'enableFocusBorder',
		dividerBorderColor: 'enableDividerBorder',
		dividerBorderWidth: 'enableDividerBorder',
		dividerBorderStyle: 'enableDividerBorder',
	};

	// Reset CSS variables for disabled toggles to prevent unwanted inheritance
	if ( attributes.enableFocusBorder === false ) {
		styles[ '--tabs-focus-border-color' ] = 'transparent';
		styles[ '--tabs-focus-border-color-active' ] = 'transparent';
		styles[ '--tabs-focus-border-width' ] = '0';
		styles[ '--tabs-focus-border-style' ] = 'none';
	}

	if ( attributes.enableDividerBorder === false ) {
		styles[ '--tabs-divider-border-color' ] = 'transparent';
		styles[ '--tabs-divider-border-width' ] = '0';
		styles[ '--tabs-divider-border-style' ] = 'none';
	}

	// Process each attribute using schema-generated mappings
	Object.entries( attributes ).forEach( ( [ attrName, value ] ) => {
		if ( value === null || value === undefined ) {
			return;
		}

		// Skip toggle attributes themselves
		if ( attrName === 'enableFocusBorder' || attrName === 'enableDividerBorder' ) {
			return;
		}

		// Check if this attribute is controlled by a toggle and if that toggle is disabled
		const controllingToggle = toggledAttributes[ attrName ];
		if ( controllingToggle && ! attributes[ controllingToggle ] ) {
			return;
		}

		// Get CSS variable name from generated mappings
		const cssVar = getCssVarName( attrName, 'tabs' );
		if ( ! cssVar ) {
			return;
		}

		// Format value with proper unit from generated mappings
		const formattedValue = formatCssValue( attrName, value, 'tabs' );
		if ( formattedValue !== null ) {
			styles[ cssVar ] = formattedValue;
		}
	} );

	return styles;
}

export default getCustomizationStyles;
