/**
 * Accordion Block - Save Component
 *
 * Renders the frontend HTML structure with proper ARIA attributes.
 * Applies theme class names and only outputs inline CSS for explicit customizations.
 * Uses hybrid Tier 2 CSS approach for optimal performance.
 *
 * @package
 * @since 1.0.0
 */

import { useBlockProps, RichText } from '@wordpress/block-editor';
import { getAllEffectiveValues, getAccordionButtonAria, getAccordionPanelAria } from '@shared';

/**
 * Accordion Save Component
 *
 * @param {Object} props            Block props
 * @param {Object} props.attributes Block attributes
 * @return {JSX.Element} Save component
 */
export default function Save( { attributes } ) {
	// Get CSS defaults (will be available via wp_localize_script in frontend)
	const cssDefaults = window.accordionDefaults || {};

	// Get effective values for display purposes (icon rendering, etc.)
	const effectiveValues = getAllEffectiveValues(
		attributes,
		{}, // Themes are resolved server-side via CSS classes
		cssDefaults,
		'accordion'
	);

	const accordionId = attributes.accordionId || '';
	const buttonId = `${ accordionId }-btn`;
	const panelId = `${ accordionId }-panel`;

	/**
	 * Build inline CSS variables ONLY for explicit customizations (Tier 3)
	 * Theme values (Tier 2) are applied via CSS classes generated by PHP
	 * CSS defaults (Tier 1) are in the stylesheet
	 */
	const getCustomizationStyles = () => {
		const styles = {};

		// Helper to add style if attribute is explicitly defined
		const addIfDefined = ( attrName, cssVar, formatter ) => {
			if ( attributes[ attrName ] !== null && attributes[ attrName ] !== undefined ) {
				styles[ cssVar ] = formatter ? formatter( attributes[ attrName ] ) : attributes[ attrName ];
			}
		};

		// Simple string/color values
		addIfDefined( 'titleBackgroundColor', '--accordion-title-bg' );
		addIfDefined( 'titleColor', '--accordion-title-color' );
		addIfDefined( 'titleFontWeight', '--accordion-title-font-weight' );
		addIfDefined( 'titleFontStyle', '--accordion-title-font-style' );
		addIfDefined( 'titleTextTransform', '--accordion-title-text-transform' );
		addIfDefined( 'titleTextDecoration', '--accordion-title-text-decoration' );
		addIfDefined( 'titleAlignment', '--accordion-title-alignment' );
		addIfDefined( 'contentBackgroundColor', '--accordion-content-bg' );
		addIfDefined( 'contentColor', '--accordion-content-color' );
		addIfDefined( 'accordionBorderStyle', '--accordion-border-style' );
		addIfDefined( 'accordionBorderColor', '--accordion-border-color' );
		addIfDefined( 'accordionShadow', '--accordion-shadow' );
		addIfDefined( 'dividerBorderStyle', '--accordion-divider-style' );
		addIfDefined( 'dividerBorderColor', '--accordion-divider-color' );
		addIfDefined( 'iconColor', '--accordion-icon-color' );
		addIfDefined( 'hoverTitleBackgroundColor', '--accordion-hover-title-bg' );
		addIfDefined( 'hoverTitleColor', '--accordion-hover-title-color' );
		addIfDefined( 'activeTitleBackgroundColor', '--accordion-active-title-bg' );
		addIfDefined( 'activeTitleColor', '--accordion-active-title-color' );

		// Numeric values with units
		addIfDefined( 'titleFontSize', '--accordion-title-font-size', ( val ) => `${ val }px` );
		addIfDefined( 'accordionBorderThickness', '--accordion-border-width', ( val ) => `${ val }px` );
		addIfDefined( 'accordionMarginBottom', '--accordion-margin-bottom', ( val ) => `${ val }px` );
		addIfDefined( 'dividerBorderThickness', '--accordion-divider-width', ( val ) => `${ val }px` );
		addIfDefined( 'iconSize', '--accordion-icon-size', ( val ) => `${ val }px` );
		addIfDefined( 'iconRotation', '--accordion-icon-rotation', ( val ) => `${ val }deg` );

		// Object values (padding, border radius)
		if ( attributes.titlePadding ) {
			const p = attributes.titlePadding;
			styles[ '--accordion-title-padding' ] = `${ p.top }px ${ p.right }px ${ p.bottom }px ${ p.left }px`;
		}
		if ( attributes.contentPadding ) {
			const p = attributes.contentPadding;
			styles[ '--accordion-content-padding' ] = `${ p.top }px ${ p.right }px ${ p.bottom }px ${ p.left }px`;
		}
		if ( attributes.accordionBorderRadius ) {
			const br = attributes.accordionBorderRadius;
			styles[ '--accordion-border-radius' ] = `${ br.topLeft }px ${ br.topRight }px ${ br.bottomRight }px ${ br.bottomLeft }px`;
		}

		return styles;
	};

	const customizationStyles = getCustomizationStyles();

	/**
	 * Render icon based on settings
	 */
	const renderIcon = () => {
		if ( ! effectiveValues.showIcon ) {
			return null;
		}

		const iconContent = effectiveValues.iconTypeClosed || '▾';
		const iconOpen = effectiveValues.iconTypeOpen;
		const isImage = iconContent.startsWith( 'http' );

		if ( isImage ) {
			return (
				<img
					src={ iconContent }
					alt=""
					aria-hidden="true"
					className="accordion-icon accordion-icon-image"
					data-icon-closed={ iconContent }
					data-icon-open={ iconOpen !== 'none' ? iconOpen : iconContent }
				/>
			);
		}

		return (
			<span
				className="accordion-icon"
				aria-hidden="true"
				data-icon-closed={ iconContent }
				data-icon-open={ iconOpen !== 'none' ? iconOpen : iconContent }
			>
				{ iconContent }
			</span>
		);
	};

	/**
	 * Render title with optional heading wrapper
	 */
	const renderTitle = () => {
		const headingLevel = effectiveValues.headingLevel || 'none';
		const iconPosition = effectiveValues.iconPosition || 'right';

		// ARIA attributes for button
		const buttonAria = getAccordionButtonAria(
			buttonId,
			panelId,
			attributes.initiallyOpen || false
		);

		const buttonContent = (
			<button
				type="button"
				className={ `accordion-title ${ iconPosition ? `icon-${ iconPosition }` : '' }` }
				{ ...buttonAria }
			>
				{ ( iconPosition === 'left' || iconPosition === 'extreme-left' ) && renderIcon() }
				<RichText.Content
					tagName="span"
					value={ attributes.title || '' }
					className="accordion-title-text"
				/>
				{ ( iconPosition === 'right' || iconPosition === 'extreme-right' ) && renderIcon() }
			</button>
		);

		if ( headingLevel !== 'none' ) {
			const HeadingTag = headingLevel;
			return <HeadingTag className="accordion-heading">{ buttonContent }</HeadingTag>;
		}

		return buttonContent;
	};

	// ARIA attributes for panel
	const panelAria = getAccordionPanelAria( panelId, buttonId );

	// Build class names - add theme class if using a theme
	const classNames = [ 'wp-block-accordion' ];
	if ( attributes.currentTheme ) {
		// Sanitize theme ID for CSS class (alphanumeric and hyphens only)
		const safeThemeId = attributes.currentTheme.replace( /[^a-zA-Z0-9\-]/g, '' );
		classNames.push( `accordion-theme-${ safeThemeId }` );
	}

	const blockProps = useBlockProps.save( {
		className: classNames.join( ' ' ),
		'data-accordion-id': accordionId,
		'data-allow-multiple': attributes.allowMultipleOpen || false,
		// Only add inline styles if there are customizations
		...( Object.keys( customizationStyles ).length > 0 && { style: customizationStyles } ),
	} );

	return (
		<div { ...blockProps }>
			<div
				className={ `accordion-item ${ attributes.initiallyOpen ? 'is-open' : '' }` }
				data-item-id="0"
			>
				{ renderTitle() }

				<div
					className="accordion-content"
					{ ...panelAria }
					{ ...( ! attributes.initiallyOpen && { hidden: true } ) }
				>
					<RichText.Content
						tagName="div"
						value={ attributes.content || '' }
						className="accordion-content-text"
					/>
				</div>
			</div>
		</div>
	);
}
