/**
 * Accordion Block - Save Component
 *
 * Renders the frontend HTML structure with proper ARIA attributes.
 * Applies theme class names and only outputs inline CSS for explicit customizations.
 * Uses hybrid Tier 2 CSS approach for optimal performance.
 *
 * @package
 * @since 1.0.0
 */

import { useBlockProps, RichText, InnerBlocks } from '@wordpress/block-editor';
import { getAllEffectiveValues, getAccordionButtonAria, getAccordionPanelAria } from '@shared';

/**
 * Accordion Save Component
 *
 * @param {Object} props            Block props
 * @param {Object} props.attributes Block attributes
 * @return {JSX.Element} Save component
 */
export default function Save( { attributes } ) {
	// Get CSS defaults (will be available via wp_localize_script in frontend)
	const cssDefaults = window.accordionDefaults || {};

	// Get effective values for display purposes (icon rendering, etc.)
	const effectiveValues = getAllEffectiveValues(
		attributes,
		{}, // Themes are resolved server-side via CSS classes
		cssDefaults,
		'accordion'
	);

	const accordionId = attributes.accordionId || '';

	/**
	 * Build inline CSS variables ONLY for explicit customizations (Tier 3)
	 * Theme values (Tier 2) are applied via CSS classes generated by PHP
	 * CSS defaults (Tier 1) are in the stylesheet
	 */
	const getCustomizationStyles = () => {
		const styles = {};

		// Get the current theme's values to determine what's truly customized
		// If a value matches the theme, don't output it inline
		const currentTheme = attributes.currentTheme || '';
		const themeValues = window.accordionThemes ? window.accordionThemes[ currentTheme ] : {};

		// Helper to add style if attribute is explicitly defined AND differs from theme
		const addIfDefined = ( attrName, cssVar, formatter ) => {
			if ( attributes[ attrName ] !== null && attributes[ attrName ] !== undefined ) {
				const value = formatter ? formatter( attributes[ attrName ] ) : attributes[ attrName ];

				// Check if this value is part of current theme
				// If it matches the theme value, don't output inline (let theme CSS handle it)
				if ( currentTheme && themeValues[ attrName ] !== undefined ) {
					const themeValue = formatter ? formatter( themeValues[ attrName ] ) : themeValues[ attrName ];
					if ( value === themeValue ) {
						return; // Skip - this is a theme value, not a customization
					}
				}

				// Only output if it's a true customization (different from theme)
				styles[ cssVar ] = value;
			}
		};

		// Simple string/color values
		addIfDefined( 'titleBackgroundColor', '--accordion-title-bg' );
		addIfDefined( 'titleColor', '--accordion-title-color' );
		addIfDefined( 'hoverTitleBackgroundColor', '--accordion-title-hover-bg' );
		addIfDefined( 'hoverTitleColor', '--accordion-title-hover-color' );
		addIfDefined( 'titleFontWeight', '--accordion-title-font-weight' );
		addIfDefined( 'titleFontStyle', '--accordion-title-font-style' );
		addIfDefined( 'titleTextTransform', '--accordion-title-text-transform' );
		addIfDefined( 'titleTextDecoration', '--accordion-title-text-decoration' );
		addIfDefined( 'titleAlignment', '--accordion-title-alignment' );
		addIfDefined( 'contentBackgroundColor', '--accordion-content-bg' );
		addIfDefined( 'contentColor', '--accordion-content-color' );
		addIfDefined( 'accordionBorderStyle', '--accordion-border-style' );
		addIfDefined( 'accordionBorderColor', '--accordion-border-color' );
		addIfDefined( 'accordionShadow', '--accordion-shadow' );
		addIfDefined( 'dividerBorderStyle', '--accordion-divider-style' );
		addIfDefined( 'dividerBorderColor', '--accordion-divider-color' );
		addIfDefined( 'iconColor', '--accordion-icon-color' );

		// Numeric values with units
		addIfDefined( 'titleFontSize', '--accordion-title-font-size', ( val ) => `${ val }px` );
		addIfDefined( 'accordionBorderThickness', '--accordion-border-width', ( val ) => `${ val }px` );
		addIfDefined( 'dividerBorderThickness', '--accordion-divider-width', ( val ) => `${ val }px` );
		addIfDefined( 'iconSize', '--accordion-icon-size', ( val ) => `${ val }px` );

		// Icon rotation - only output if different from default (180deg)
		if ( attributes.iconRotation !== null && attributes.iconRotation !== undefined && attributes.iconRotation !== 180 ) {
			styles[ '--accordion-icon-rotation' ] = `${ attributes.iconRotation }deg`;
		}

		// Object values (border radius)
		if ( attributes.accordionBorderRadius ) {
			const br = attributes.accordionBorderRadius;
			const brValue = `${ br.topLeft }px ${ br.topRight }px ${ br.bottomRight }px ${ br.bottomLeft }px`;

			// Check if this matches the theme value (don't output inline if it does)
			if ( currentTheme && themeValues.accordionBorderRadius !== undefined ) {
				const themeBr = themeValues.accordionBorderRadius;
				const themeBrValue = `${ themeBr.topLeft }px ${ themeBr.topRight }px ${ themeBr.bottomRight }px ${ themeBr.bottomLeft }px`;
				if ( brValue === themeBrValue ) {
					return styles; // Skip - this is a theme value, not a customization
				}
			}

			styles[ '--accordion-border-radius' ] = brValue;
		}

		// Width (non-CSS variable value as inline style)
		// Only output if width is not the default 100%
		if ( attributes.accordionWidth && attributes.accordionWidth !== '100%' ) {
			styles.width = attributes.accordionWidth;
		}

		return styles;
	};

	const customizationStyles = getCustomizationStyles();

	/**
	 * Render icon based on settings
	 */
	const renderIcon = () => {
		if ( ! effectiveValues.showIcon ) {
			return null;
		}

		const iconContent = effectiveValues.iconTypeClosed || '▾';
		const iconOpen = effectiveValues.iconTypeOpen;
		const isImage = iconContent.startsWith( 'http' );

		if ( isImage ) {
			return (
				<img
					src={ iconContent }
					alt=""
					aria-hidden="true"
					className="accordion-icon accordion-icon-image"
					data-icon-closed={ iconContent }
					data-icon-open={ iconOpen !== 'none' ? iconOpen : iconContent }
				/>
			);
		}

		return (
			<span
				className="accordion-icon"
				aria-hidden="true"
				data-icon-closed={ iconContent }
				data-icon-open={ iconOpen !== 'none' ? iconOpen : iconContent }
			>
				{ iconContent }
			</span>
		);
	};

	/**
	 * Render title with optional heading wrapper
	 */
	const renderTitle = () => {
		const headingLevel = effectiveValues.headingLevel || 'none';
		const iconPosition = effectiveValues.iconPosition || 'right';
		const titleAlignment = effectiveValues.titleAlignment || 'left';

		// ARIA attributes for button
		const buttonAria = getAccordionButtonAria(
			accordionId,
			attributes.initiallyOpen || false
		);

		// Build button content - icon position affects layout structure
		let buttonChildren;

		if ( iconPosition === 'extreme-left' ) {
			// Extreme left: icon at far left, text with flex grows to fill
			buttonChildren = (
				<>
					{ renderIcon() }
					<RichText.Content
						tagName="span"
						value={ attributes.title || '' }
						className="accordion-title-text"
					/>
				</>
			);
		} else if ( iconPosition === 'extreme-right' ) {
			// Extreme right: text with flex grows, icon at far right
			buttonChildren = (
				<>
					<RichText.Content
						tagName="span"
						value={ attributes.title || '' }
						className="accordion-title-text"
					/>
					{ renderIcon() }
				</>
			);
		} else if ( iconPosition === 'left' ) {
			// Left of text: wrap icon+text as single group that can be aligned
			buttonChildren = (
				<div style={ { display: 'flex', alignItems: 'center', justifyContent: titleAlignment } }>
					{ renderIcon() }
					<RichText.Content
						tagName="span"
						value={ attributes.title || '' }
						className="accordion-title-text"
					/>
				</div>
			);
		} else {
			// Right of text (default): wrap text+icon as single group that can be aligned
			buttonChildren = (
				<div style={ { display: 'flex', alignItems: 'center', justifyContent: titleAlignment } }>
					<RichText.Content
						tagName="span"
						value={ attributes.title || '' }
						className="accordion-title-text"
					/>
					{ renderIcon() }
				</div>
			);
		}

		const buttonContent = (
			<button
				type="button"
				className={ `accordion-title ${ iconPosition ? `icon-${ iconPosition }` : '' }` }
				{ ...buttonAria }
				style={ { justifyContent: ( iconPosition === 'extreme-left' || iconPosition === 'extreme-right' ) ? 'space-between' : titleAlignment } }
			>
				{ buttonChildren }
			</button>
		);

		if ( headingLevel !== 'none' ) {
			const HeadingTag = headingLevel;
			return <HeadingTag className="accordion-heading">{ buttonContent }</HeadingTag>;
		}

		return buttonContent;
	};

	// ARIA attributes for panel
	const panelAria = getAccordionPanelAria( accordionId );

	// Build class names - add theme class if using a theme
	const classNames = [ 'wp-block-accordion', 'sammu-blocks' ];
	if ( attributes.currentTheme ) {
		// Sanitize theme ID for CSS class (alphanumeric and hyphens only)
		const safeThemeId = attributes.currentTheme.replace( /[^a-zA-Z0-9\-]/g, '' );
		classNames.push( `accordion-theme-${ safeThemeId }` );
	}

	// Add alignment class
	const alignmentClass = attributes.accordionHorizontalAlign
		? `sammu-blocks-align-${ attributes.accordionHorizontalAlign }`
		: 'sammu-blocks-align-left';
	classNames.push( alignmentClass );

	const blockProps = useBlockProps.save( {
		className: classNames.join( ' ' ),
		'data-accordion-id': accordionId,
		// Add customization styles (colors, etc.) - alignment is now handled by CSS classes
		...( Object.keys( customizationStyles ).length > 0 && { style: customizationStyles } ),
	} );

	return (
		<div { ...blockProps }>
			<div
				className={ `accordion-item ${ attributes.initiallyOpen ? 'is-open' : '' }` }
				data-item-id="0"
			>
				{ renderTitle() }

				<div
					className="accordion-content"
					{ ...panelAria }
					{ ...( ! attributes.initiallyOpen && { hidden: true } ) }
				>
					<div className="accordion-content-inner">
						<InnerBlocks.Content />
					</div>
				</div>
			</div>
		</div>
	);
}
