/**
 * Accordion Block - Save Component
 *
 * Renders the frontend HTML structure with proper ARIA attributes.
 * Applies theme class names and only outputs inline CSS for explicit customizations.
 * Uses hybrid Tier 2 CSS approach for optimal performance.
 *
 * IMPORTANT: Sections marked with AUTO-GENERATED comments are automatically
 * regenerated from the schema on every build. Do not edit code between these markers.
 *
 * To modify styles:
 * 1. Edit the schema: schemas/accordion.json
 * 2. Run: npm run schema:build
 * 3. The code between markers will update automatically
 *
 * @package
 * @since 1.0.0
 */

import { useBlockProps, RichText, InnerBlocks } from '@wordpress/block-editor';
import { getAllEffectiveValues, getAccordionButtonAria, getAccordionPanelAria, getAllDefaults, getAlignmentClass } from '@shared';
import { formatCssValue, getCssVarName } from '@shared/config/css-var-mappings-generated';
import { accordionAttributes } from './accordion-attributes';

/**
 * Accordion Save Component
 *
 * @param {Object} props            Block props
 * @param {Object} props.attributes Block attributes
 * @return {JSX.Element} Save component
 */
export default function Save( { attributes } ) {
	// Extract schema defaults (single source of truth)
	const schemaDefaults = {};
	Object.keys( accordionAttributes ).forEach( ( key ) => {
		if ( accordionAttributes[ key ].default !== undefined ) {
			schemaDefaults[ key ] = accordionAttributes[ key ].default;
		}
	} );
	const allDefaults = getAllDefaults( schemaDefaults );

	// Get effective values for display purposes (icon rendering, etc.)
	const effectiveValues = getAllEffectiveValues(
		attributes,
		{}, // Themes are resolved server-side via CSS classes
		allDefaults,
		'accordion'
	);

	const accordionId = attributes.accordionId || '';

	/**
	 * Build inline CSS variables ONLY for explicit customizations (Tier 3)
	 * Theme values (Tier 2) are applied via CSS classes generated by PHP
	 * CSS defaults (Tier 1) are in the stylesheet
	 *
	 * The `customizations` attribute contains ONLY deltas from expected values
	 * (calculated in edit.js by comparing attributes to defaults + theme)
	 *
	 * Uses auto-generated mappings from schema (single source of truth)
	 */
	/* ========== AUTO-GENERATED-CUSTOMIZATION-STYLES-START ========== */
// DO NOT EDIT - This code is auto-generated from schema
const getCustomizationStyles = () => {
  const styles = {};

  // Get customizations (deltas from expected values, calculated in edit.js)
  const customizations = attributes.customizations || {};

  // Process each customization using schema-generated mappings
  Object.entries(customizations).forEach(([attrName, value]) => {
    if (value === null || value === undefined) {
      return;
    }

    // Get CSS variable name from generated mappings
    const cssVar = getCssVarName(attrName, 'accordion');
    if (!cssVar) {
      return; // Attribute not mapped to a CSS variable
    }

    // Format value with proper unit from generated mappings
    const formattedValue = formatCssValue(attrName, value, 'accordion');
    if (formattedValue !== null) {
      styles[cssVar] = formattedValue;
    }
  });

  return styles;
};
/* ========== AUTO-GENERATED-CUSTOMIZATION-STYLES-END ========== */

	const customizationStyles = getCustomizationStyles();

	/**
	 * Render icon based on settings
	 */
	const renderIcon = () => {
		if ( ! effectiveValues.showIcon ) {
			return null;
		}

		const iconContent = effectiveValues.iconTypeClosed || '▾';
		const iconOpen = effectiveValues.iconTypeOpen;
		const isImage = iconContent.startsWith( 'http' );

		if ( isImage ) {
			return (
				<img
					src={ iconContent }
					alt=""
					aria-hidden="true"
					className="accordion-icon accordion-icon-image"
					data-icon-closed={ iconContent }
					data-icon-open={ iconOpen !== 'none' ? iconOpen : iconContent }
				/>
			);
		}

		return (
			<span
				className="accordion-icon"
				aria-hidden="true"
				data-icon-closed={ iconContent }
				data-icon-open={ iconOpen !== 'none' ? iconOpen : iconContent }
			>
				{ iconContent }
			</span>
		);
	};

	/**
	 * Render title with optional heading wrapper
	 */
	const renderTitle = () => {
		const headingLevel = effectiveValues.headingLevel || 'none';
		const iconPosition = effectiveValues.iconPosition || 'right';
		const titleAlignment = effectiveValues.titleAlignment || 'left';
		const titleAlignClass = titleAlignment ? `title-align-${ titleAlignment }` : 'title-align-left';

		// ARIA attributes for button
		const buttonAria = getAccordionButtonAria(
			accordionId,
			attributes.initiallyOpen || false
		);

		const iconElement = renderIcon();
		const hasIcon = !! iconElement;

		// Build button content - icon position affects layout structure
		let buttonChildren;

		if ( iconPosition === 'extreme-left' ) {
			// Extreme left: icon at far left, text with flex grows to fill
			buttonChildren = (
				<>
					{ hasIcon && (
						<span className="accordion-icon-slot">
							{ iconElement }
						</span>
					) }
					<div className="accordion-title-text-wrapper">
						<RichText.Content
							tagName="span"
							value={ attributes.title || '' }
							className="accordion-title-text"
						/>
					</div>
				</>
			);
		} else if ( iconPosition === 'extreme-right' ) {
			// Extreme right: text with flex grows, icon at far right
			buttonChildren = (
				<>
					<div className="accordion-title-text-wrapper">
						<RichText.Content
							tagName="span"
							value={ attributes.title || '' }
							className="accordion-title-text"
						/>
					</div>
					{ hasIcon && (
						<span className="accordion-icon-slot">
							{ iconElement }
						</span>
					) }
				</>
			);
		} else if ( iconPosition === 'left' ) {
			// Left of text: wrap icon+text as single group that can be aligned
			buttonChildren = (
				<div className="accordion-title-inline">
					{ hasIcon && iconElement }
					<RichText.Content
						tagName="span"
						value={ attributes.title || '' }
						className="accordion-title-text"
					/>
				</div>
			);
		} else {
			// Right of text (default): wrap text+icon as single group that can be aligned
			buttonChildren = (
				<div className="accordion-title-inline">
					<RichText.Content
						tagName="span"
						value={ attributes.title || '' }
						className="accordion-title-text"
					/>
					{ hasIcon && iconElement }
				</div>
			);
		}

		const buttonContent = (
			<button
				type="button"
				className={ `accordion-title ${ iconPosition ? `icon-${ iconPosition }` : '' } ${ titleAlignClass }` }
				{ ...buttonAria }
			>
				{ buttonChildren }
			</button>
		);

		if ( headingLevel !== 'none' ) {
			const HeadingTag = headingLevel;
			return <HeadingTag className="accordion-heading">{ buttonContent }</HeadingTag>;
		}

		return buttonContent;
	};

	// ARIA attributes for panel
	const panelAria = getAccordionPanelAria( accordionId );

	// Build class names - accordion-item is now the root element
	const classNames = [ 'gutplus-accordion' ];

	// Add open state class
	if ( attributes.initiallyOpen ) {
		classNames.push( 'is-open' );
	}

	// Add theme class if using a theme
	if ( attributes.currentTheme ) {
		// Sanitize theme ID for CSS class (alphanumeric and hyphens only)
		const safeThemeId = attributes.currentTheme.replace( /[^a-zA-Z0-9\-]/g, '' );
		classNames.push( `gutplus-accordion-theme-${ safeThemeId }` );
	}

	// Add alignment class
	const alignmentClass = getAlignmentClass( attributes.accordionHorizontalAlign );
	classNames.push( alignmentClass );

	const blockProps = useBlockProps.save( {
		className: classNames.join( ' ' ),
		'data-accordion-id': accordionId,
		// Add customization styles (colors, etc.) - alignment is now handled by CSS classes
		...( Object.keys( customizationStyles ).length > 0 && { style: customizationStyles } ),
	} );

	return (
		<div { ...blockProps }>
			<div className="accordion-title-wrapper">
				{ renderTitle() }
			</div>

			<div
				className="accordion-content"
				{ ...panelAria }
				{ ...( ! attributes.initiallyOpen && { hidden: true } ) }
			>
				<div className="accordion-content-inner">
					<InnerBlocks.Content />
				</div>
			</div>
		</div>
	);
}
