/**
 * Zod Validation Schema for Table of Contents Block
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: schemas/toc.json
 * Generated at: 2025-12-22T19:13:33.426Z
 *
 * This file is regenerated on every build. Any manual changes will be lost.
 * To modify this file, update the source schema and run: npm run schema:build
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

import { z } from 'zod';

/**
 * Validation schema for Table of Contents theme values
 */
export const tocThemeSchema = z.object({
  wrapperBackgroundColor: z.string(),
  blockBorderColor: z.string(),
  titleColor: z.string(),
  titleBackgroundColor: z.string(),
  linkColor: z.string(),
  linkHoverColor: z.string(),
  linkActiveColor: z.string(),
  linkVisitedColor: z.string(),
  numberingColor: z.string(),
  h1Color: z.string(),
  h1FontSize: z.number(),
  h1FontWeight: z.string(),
  h1FontStyle: z.string(),
  h1TextTransform: z.string(),
  h1TextDecoration: z.string(),
  h2Color: z.string(),
  h2FontSize: z.number(),
  h2FontWeight: z.string(),
  h2FontStyle: z.string(),
  h2TextTransform: z.string(),
  h2TextDecoration: z.string(),
  h3Color: z.string(),
  h3FontSize: z.number(),
  h3FontWeight: z.string(),
  h3FontStyle: z.string(),
  h3TextTransform: z.string(),
  h3TextDecoration: z.string(),
  h4Color: z.string(),
  h4FontSize: z.number(),
  h4FontWeight: z.string(),
  h4FontStyle: z.string(),
  h4TextTransform: z.string(),
  h4TextDecoration: z.string(),
  h5Color: z.string(),
  h5FontSize: z.number(),
  h5FontWeight: z.string(),
  h5FontStyle: z.string(),
  h5TextTransform: z.string(),
  h5TextDecoration: z.string(),
  h6Color: z.string(),
  h6FontSize: z.number(),
  h6FontWeight: z.string(),
  h6FontStyle: z.string(),
  h6TextTransform: z.string(),
  h6TextDecoration: z.string(),
  collapseIconColor: z.string(),
  titleFontSize: z.number(),
  titleFontWeight: z.string(),
  titleTextTransform: z.string(),
  titleAlignment: z.string(),
  titlePadding: z.record(z.any()),
  blockBorderWidth: z.number(),
  blockBorderStyle: z.string(),
  blockBorderRadius: z.record(z.any()),
  blockShadow: z.string(),
  blockShadowHover: z.string(),
  wrapperPadding: z.number(),
  listPaddingLeft: z.number(),
  itemSpacing: z.number(),
  levelIndent: z.string(),
  positionTop: z.number(),
  zIndex: z.number(),
  collapseIconSize: z.number(),
});

/**
 * Validation schema for all Table of Contents block attributes
 */
export const tocAttributesSchema = z.object({
  tocId: z.string(),
  showTitle: z.boolean(),
  titleText: z.string(),
  currentTheme: z.string(),
  tocItems: z.array(z.any()),
  deletedHeadingIds: z.array(z.any()),
  filterMode: z.string(),
  includeLevels: z.array(z.any()),
  includeClasses: z.string(),
  excludeLevels: z.array(z.any()),
  excludeClasses: z.string(),
  depthLimit: z.number().optional(),
  includeAccordions: z.boolean(),
  includeTabs: z.boolean(),
  numberingStyle: z.string(),
  isCollapsible: z.boolean(),
  initiallyCollapsed: z.boolean(),
  positionType: z.string(),
  smoothScroll: z.boolean(),
  scrollOffset: z.number(),
  autoHighlight: z.boolean(),
  clickBehavior: z.string(),
  tocWidth: z.string(),
  tocHorizontalAlign: z.string(),
  wrapperBackgroundColor: z.string(),
  blockBorderColor: z.string(),
  titleColor: z.string(),
  titleBackgroundColor: z.string(),
  linkColor: z.string(),
  linkHoverColor: z.string(),
  linkActiveColor: z.string(),
  linkVisitedColor: z.string(),
  numberingColor: z.string(),
  h1Color: z.string(),
  h1FontSize: z.number(),
  h1FontWeight: z.string(),
  h1FontStyle: z.string(),
  h1TextTransform: z.string(),
  h1TextDecoration: z.string(),
  h2Color: z.string(),
  h2FontSize: z.number(),
  h2FontWeight: z.string(),
  h2FontStyle: z.string(),
  h2TextTransform: z.string(),
  h2TextDecoration: z.string(),
  h3Color: z.string(),
  h3FontSize: z.number(),
  h3FontWeight: z.string(),
  h3FontStyle: z.string(),
  h3TextTransform: z.string(),
  h3TextDecoration: z.string(),
  h4Color: z.string(),
  h4FontSize: z.number(),
  h4FontWeight: z.string(),
  h4FontStyle: z.string(),
  h4TextTransform: z.string(),
  h4TextDecoration: z.string(),
  h5Color: z.string(),
  h5FontSize: z.number(),
  h5FontWeight: z.string(),
  h5FontStyle: z.string(),
  h5TextTransform: z.string(),
  h5TextDecoration: z.string(),
  h6Color: z.string(),
  h6FontSize: z.number(),
  h6FontWeight: z.string(),
  h6FontStyle: z.string(),
  h6TextTransform: z.string(),
  h6TextDecoration: z.string(),
  collapseIconColor: z.string(),
  titleFontSize: z.number(),
  titleFontWeight: z.string(),
  titleTextTransform: z.string(),
  titleAlignment: z.string(),
  titlePadding: z.record(z.any()),
  blockBorderWidth: z.number(),
  blockBorderStyle: z.string(),
  blockBorderRadius: z.record(z.any()),
  blockShadow: z.string(),
  blockShadowHover: z.string(),
  wrapperPadding: z.number(),
  listPaddingLeft: z.number(),
  itemSpacing: z.number(),
  enableHierarchicalIndent: z.boolean(),
  levelIndent: z.string(),
  positionTop: z.number(),
  zIndex: z.number(),
  positionHorizontalSide: z.string(),
  positionHorizontalOffset: z.string(),
  collapseIconSize: z.number(),
});

// Type inference exports
export type TocTheme = z.infer<typeof tocThemeSchema>;
export type TocAttributes = z.infer<typeof tocAttributesSchema>;
