/**
 * Zod Validation Schema for Table of Contents Block
 *
 * AUTO-GENERATED FILE - DO NOT EDIT MANUALLY
 * Generated from: schemas/toc.json
 * Generated at: 2026-01-04T23:18:45.233Z
 *
 * This file is regenerated on every build. Any manual changes will be lost.
 * To modify this file, update the source schema and run: npm run schema:build
 *
 * @package GuttemberPlus
 * @since 1.0.0
 */

import { z } from 'zod';

/**
 * Validation schema for Table of Contents theme values
 */
export const tocThemeSchema = z.object({
  includeH1: z.boolean(),
  includeH2: z.boolean(),
  includeH3: z.boolean(),
  includeH4: z.boolean(),
  includeH5: z.boolean(),
  includeH6: z.boolean(),
  includeLevels: z.array(z.any()),
  includeClasses: z.string(),
  excludeLevels: z.array(z.any()),
  excludeClasses: z.string(),
  includeAccordions: z.boolean(),
  includeTabs: z.boolean(),
  positionType: z.string(),
  smoothScroll: z.boolean(),
  scrollOffset: z.number(),
  autoHighlight: z.boolean(),
  clickBehavior: z.string(),
  wrapperBackgroundColor: z.string(),
  blockBorderColor: z.record(z.any()),
  unifiedLinkColors: z.boolean(),
  h1NumberingStyle: z.string(),
  h2NumberingStyle: z.string(),
  h3NumberingStyle: z.string(),
  h4NumberingStyle: z.string(),
  h5NumberingStyle: z.string(),
  h6NumberingStyle: z.string(),
  h1FontSize: z.string(),
  h1FontWeight: z.string(),
  h1FontStyle: z.string(),
  h1TextTransform: z.string(),
  h1TextDecoration: z.string(),
  h2FontSize: z.string(),
  h2FontWeight: z.string(),
  h2FontStyle: z.string(),
  h2TextTransform: z.string(),
  h2TextDecoration: z.string(),
  h3FontSize: z.string(),
  h3FontWeight: z.string(),
  h3FontStyle: z.string(),
  h3TextTransform: z.string(),
  h3TextDecoration: z.string(),
  h4FontSize: z.string(),
  h4FontWeight: z.string(),
  h4FontStyle: z.string(),
  h4TextTransform: z.string(),
  h4TextDecoration: z.string(),
  h5FontSize: z.string(),
  h5FontWeight: z.string(),
  h5FontStyle: z.string(),
  h5TextTransform: z.string(),
  h5TextDecoration: z.string(),
  h6FontSize: z.string(),
  h6FontWeight: z.string(),
  h6FontStyle: z.string(),
  h6TextTransform: z.string(),
  h6TextDecoration: z.string(),
  showIcon: z.boolean(),
  useDifferentIcons: z.boolean(),
  iconPosition: z.string(),
  iconRotation: z.string(),
  iconInactiveSource: z.record(z.any()),
  iconInactiveColor: z.string(),
  iconInactiveRotation: z.string(),
  iconInactiveSize: z.string(),
  iconInactiveMaxSize: z.string(),
  iconInactiveOffsetX: z.string(),
  iconInactiveOffsetY: z.string(),
  iconActiveSource: z.record(z.any()),
  iconActiveColor: z.string(),
  iconActiveRotation: z.string(),
  iconActiveSize: z.string(),
  iconActiveMaxSize: z.string(),
  iconActiveOffsetX: z.string(),
  iconActiveOffsetY: z.string(),
  titleFontSize: z.string(),
  titleFontWeight: z.string(),
  titleFontStyle: z.string(),
  titleTextTransform: z.string(),
  titleTextDecoration: z.string(),
  titleAlignment: z.string(),
  blockBorderWidth: z.string(),
  blockBorderStyle: z.record(z.any()),
  blockBorderRadius: z.record(z.any()),
  blockShadow: z.string(),
  blockShadowHover: z.string(),
  wrapperPadding: z.string(),
  itemSpacing: z.string(),
  enableHierarchicalIndent: z.boolean(),
  levelIndent: z.string(),
  positionTop: z.string(),
  zIndex: z.number(),
  positionHorizontalSide: z.string(),
  positionHorizontalOffset: z.string(),
});

/**
 * Validation schema for all Table of Contents block attributes
 */
export const tocAttributesSchema = z.object({
  tocId: z.string(),
  showTitle: z.boolean(),
  titleText: z.string(),
  currentTheme: z.string(),
  tocItems: z.array(z.any()),
  deletedHeadingIds: z.array(z.any()),
  filterMode: z.string(),
  includeH1: z.boolean(),
  includeH2: z.boolean(),
  includeH3: z.boolean(),
  includeH4: z.boolean(),
  includeH5: z.boolean(),
  includeH6: z.boolean(),
  includeLevels: z.array(z.any()),
  includeClasses: z.string(),
  excludeLevels: z.array(z.any()),
  excludeClasses: z.string(),
  includeAccordions: z.boolean(),
  includeTabs: z.boolean(),
  isCollapsible: z.boolean(),
  initiallyCollapsed: z.boolean(),
  positionType: z.string(),
  smoothScroll: z.boolean(),
  scrollOffset: z.number(),
  autoHighlight: z.boolean(),
  clickBehavior: z.string(),
  tocWidth: z.string(),
  tocHorizontalAlign: z.string(),
  wrapperBackgroundColor: z.string(),
  blockBorderColor: z.record(z.any()),
  titleColor: z.any(),
  unifiedLinkColors: z.boolean(),
  linkColor: z.any(),
  h1NumberingStyle: z.string(),
  h2NumberingStyle: z.string(),
  h3NumberingStyle: z.string(),
  h4NumberingStyle: z.string(),
  h5NumberingStyle: z.string(),
  h6NumberingStyle: z.string(),
  h1Color: z.any(),
  h1FontSize: z.string(),
  h1FontWeight: z.string(),
  h1FontStyle: z.string(),
  h1TextTransform: z.string(),
  h1TextDecoration: z.string(),
  h2Color: z.any(),
  h2FontSize: z.string(),
  h2FontWeight: z.string(),
  h2FontStyle: z.string(),
  h2TextTransform: z.string(),
  h2TextDecoration: z.string(),
  h3Color: z.any(),
  h3FontSize: z.string(),
  h3FontWeight: z.string(),
  h3FontStyle: z.string(),
  h3TextTransform: z.string(),
  h3TextDecoration: z.string(),
  h4Color: z.any(),
  h4FontSize: z.string(),
  h4FontWeight: z.string(),
  h4FontStyle: z.string(),
  h4TextTransform: z.string(),
  h4TextDecoration: z.string(),
  h5Color: z.any(),
  h5FontSize: z.string(),
  h5FontWeight: z.string(),
  h5FontStyle: z.string(),
  h5TextTransform: z.string(),
  h5TextDecoration: z.string(),
  h6Color: z.any(),
  h6FontSize: z.string(),
  h6FontWeight: z.string(),
  h6FontStyle: z.string(),
  h6TextTransform: z.string(),
  h6TextDecoration: z.string(),
  showIcon: z.boolean(),
  useDifferentIcons: z.boolean(),
  iconPosition: z.string(),
  iconRotation: z.string(),
  iconInactiveSource: z.record(z.any()),
  iconInactiveColor: z.string(),
  iconInactiveRotation: z.string(),
  iconInactiveSize: z.string(),
  iconInactiveMaxSize: z.string(),
  iconInactiveOffsetX: z.string(),
  iconInactiveOffsetY: z.string(),
  iconActiveSource: z.record(z.any()),
  iconActiveColor: z.string(),
  iconActiveRotation: z.string(),
  iconActiveSize: z.string(),
  iconActiveMaxSize: z.string(),
  iconActiveOffsetX: z.string(),
  iconActiveOffsetY: z.string(),
  titleFontSize: z.string(),
  titleFontWeight: z.string(),
  titleFontStyle: z.string(),
  titleTextTransform: z.string(),
  titleTextDecoration: z.string(),
  titleAlignment: z.string(),
  blockBorderWidth: z.string(),
  blockBorderStyle: z.record(z.any()),
  blockBorderRadius: z.record(z.any()),
  blockShadow: z.string(),
  blockShadowHover: z.string(),
  wrapperPadding: z.string(),
  itemSpacing: z.string(),
  enableHierarchicalIndent: z.boolean(),
  levelIndent: z.string(),
  positionTop: z.string(),
  zIndex: z.number(),
  positionHorizontalSide: z.string(),
  positionHorizontalOffset: z.string(),
});

// Type inference exports
export type TocTheme = z.infer<typeof tocThemeSchema>;
export type TocAttributes = z.infer<typeof tocAttributesSchema>;
